### ISSUE TITLE
Automate Helm Upgrades based on semver expressions

### ISSUE THREAD

**Issue by srueg** [fluxcd/helm-operator#12]
Would it be possible to instead of watching images for updates, watching helm charts for new versions? The `flux.weave.works/automated: "true"` annotation could be set on a `HelmRelease` CR.

**Comment by captncraig** [comment]
Should helm chart polling be done by the helm operator or by fluxd? Fluxd already has a very similar paradigm with config for the git repo and rate limiting config and all that. But helm operator interacts with chart repos and fluxd doesn't. It makes sense to me for helm-operator to watch for changes.

**Comment by andrejpetras** [comment]
Hi @stefanprodan, @hiddeco, @squaremo 

we want to use the **fluxcd** in the large project (multiple teams, multiple services) but the release process should be based on helm chart version and not the docker image version.

Are there any news or plans for this issue?

**Comment by kalebwalton** [comment]
Agree - our releasable artifact is a combo image + helm chart. The Helm chart will always have the latest image reference.

**Comment by fredgate** [comment]
Idem. I want to use fluxcd and helm operator, but I want that my config repo be updated when a new chart version is available in a helm repository (I do not want to poll a docker registry).

**Comment by hiddeco** [comment]
We are still actively tracking interest in this, and are aware of the growing interest, but are kept back by the fact that it does not belong in the Flux code base while the operator itself is not the best candidate either.

There are plans to move the image update feature from Flux to a dedicated service, once this has happened the path for this enhancement should be more clear.

**Comment by fredgate** [comment]
I agree that it is not the responsabilty of helm operator to update git repository as its role is just to deploy charts referenced by release defined in CRD in cluster.
It is more the job of flux to auto update the git repository. But effectively it must be enhanced to update different information (version of images or of charts) in different scenarios (new artifact in the docker registry, or in the helm registry). Extract update of images in a dedicated service should effectivly allow to add another service for update of charts.

**Comment by joberdick** [comment]
@fredgate @hiddeco   To clarify, what is the current thought of the operator having the ability to watch Helm repo charts for updates directly?

I agree on not necessarily having the operator update git. Right now, helm operator needs flux to get updates from helm repos. Flux is a nice tool, but way more complicated than necessary if you simply need to install updates from pure helm charts.

**Comment by fredgate** [comment]
I am not interested in the fact that the operator could update a release when a new chart is available in a Helm repository. Because for me the right approach is to have a CD pipeline based on GitOps. And Flux is perfect for that.
However Flux consider to extract in an external service, the monitoring of new images in the Docker registry and updating of the Git repository accordingly.
I think we could have a similar external service to monitor new charts in a Helm repository. This service could be configured to allow two types of updates: either by updating the manifest of the HelmRelease in the Git repository, or by modifying the HelmRelease directly in the Kubernetes cluster. In my opinion the first is the most important. But the second could then be added quite easily.

**Comment by jbalonso** [comment]
Would it make sense for `helm-operator` to report potential new chart versions in the crd's `status` field? I vaguely suggest that the operator filter down according to version matches (to avoid spamming the status). Then, `fluxcd` can review the data but maintain responsibility for applying a change policy.

**Comment by stefanprodan** [comment]
The helm-controller (part of the GitOps Toolkit) is capable of tracking semver releases and automatically upgrade a HelmRelease based on a semver range, here is an example: https://toolkit.fluxcd.io/guides/sealed-secrets/

**Comment by squaremo** [comment]
> The helm-controller (part of the GitOps Toolkit) is capable of tracking semver releases and automatically upgrade a HelmRelease based on a semver range

The original comment asked for a chart version analogue to image updates -- in GOTK, this would be a controller that monitors helm charts and commits changes to `HelmRelease` YAMLs in the git repo.

**Comment by joberdick** [comment]
> > The helm-controller (part of the GitOps Toolkit) is capable of tracking semver releases and automatically upgrade a HelmRelease based on a semver range
> 
> The original comment asked for a chart version analogue to image updates -- in GOTK, this would be a controller that monitors helm charts and commits changes to `HelmRelease` YAMLs in the git repo.

I must have missed that. I would not be asking for that. All I was after is helm operator to be able to update base on new chart version. Seems like v2 operator might have this solved.

**Comment by kingdonb** [comment]
Sorry if your issue remains unresolved. The Helm Operator is in maintenance mode, we recommend everybody upgrades to Flux v2 and Helm Controller.

A new release of Helm Operator is out this week, 1.4.4.

We will continue to support Helm Operator in maintenance mode for an indefinite period of time, and eventually archive this repository.

Please be aware that Flux v2 has a vibrant and active developer community who are actively working through minor releases and delivering new features on the way to General Availability for Flux v2.

In the mean time, this repo will still be monitored, but support is basically limited to migration issues only. I will have to close many issues today without reading them all in detail because of time constraints. If your issue is very important, you are welcome to reopen it, but due to staleness of all issues at this point a new report is more likely to be in order. Please open another issue if you have unresolved problems that prevent your migration in the appropriate Flux v2 repo.

Helm Operator releases will continue as possible for a limited time, as a courtesy for those who still cannot migrate yet, but these are strongly not recommended for ongoing production use as our strict adherence to semver backward compatibility guarantees limit many dependencies and we can only upgrade them so far without breaking compatibility. So there are likely known CVEs that cannot be resolved.

We recommend upgrading to Flux v2 which is actively maintained ASAP.

I am going to go ahead and close every issue at once today,
Thanks for participating in Helm Operator and Flux! 💚 💙
