### ISSUE TITLE
Record failed resource annotations on `HelmRelease`

### ISSUE THREAD

**Issue by squaremo** [fluxcd/helm-operator#14]
The helm-op annotator, a secondary system that tries to mark up resources with Helm information, to be interpreted by the flux daemon, tends to spam the logs when something's wrong. It runs every few seconds, and reports any failures.

To fix this, we could
 - come up with a better way of annotating resources, or otherwise getting the information across*
 - suppress some log messages, e.g., only report failures the first time.

*The requirement is that fluxd, which knows nothing about Helm, somehow knows which resources belong to a chart release, so it can mark them as such. Instead of marking each of the resources, we could stick a list of them in the FHR status.

**Comment by hiddeco** [comment]
Slightly changed the title of the issue as the logging of messages has already been suppressed to a comma separated string with resources in the logs.

**Comment by kingdonb** [comment]
Sorry if your issue remains unresolved. The Helm Operator is in maintenance mode, we recommend everybody upgrades to Flux v2 and Helm Controller.

A new release of Helm Operator is out this week, 1.4.4.

We will continue to support Helm Operator in maintenance mode for an indefinite period of time, and eventually archive this repository.

Please be aware that Flux v2 has a vibrant and active developer community who are actively working through minor releases and delivering new features on the way to General Availability for Flux v2.

In the mean time, this repo will still be monitored, but support is basically limited to migration issues only. I will have to close many issues today without reading them all in detail because of time constraints. If your issue is very important, you are welcome to reopen it, but due to staleness of all issues at this point a new report is more likely to be in order. Please open another issue if you have unresolved problems that prevent your migration in the appropriate Flux v2 repo.

Helm Operator releases will continue as possible for a limited time, as a courtesy for those who still cannot migrate yet, but these are strongly not recommended for ongoing production use as our strict adherence to semver backward compatibility guarantees limit many dependencies and we can only upgrade them so far without breaking compatibility. So there are likely known CVEs that cannot be resolved.

We recommend upgrading to Flux v2 which is actively maintained ASAP.

I am going to go ahead and close every issue at once today,
Thanks for participating in Helm Operator and Flux! 💚 💙
