### ISSUE TITLE
Provide multiarch Docker images

### ISSUE THREAD

**Issue by onedr0p** [fluxcd/helm-operator#147]
Seeing as the project uses dockerhub which supports such multiarch images (unlike quay) what could be an issue getting this set up?

**Comment by hiddeco** [comment]
Adopting official support for ARM (or any other arch) also means that we have to maintain and deliver community support for it. Given our limited amount of maintainer bandwidth it simply isn't high enough on the list of priorities for us at the moment.

It is however a valid enhancement so I am happy to keep it on the issue backlog.

**Comment by onedr0p** [comment]
As we know Go supports cross compiling out of the box. Once you get past the original setup for the Go build, pulling in the right architectures binaries for the dependencies, and image deployment there's really nothing else to maintain.

Here's my multi-arch Container image and source:

Docker image: https://hub.docker.com/r/onedr0p/helm-operator/tags
Sauce: https://gitlab.com/onedr0p/helm-operator

**Comment by PelleRavn** [comment]
@onedr0p Trying your image out on my Pi. Do you by any chance also have a Helm Repo somewhere to easy install via Helm?

**Comment by onedr0p** [comment]
@PelleRavn that is in this repo:
https://github.com/fluxcd/helm-operator/tree/master/chart/helm-operator

Feel free to peruse thru my cluster:
https://github.com/onedr0p/k3s-gitops

**Comment by kingdonb** [comment]
Sorry if your issue remains unresolved. The Helm Operator is in maintenance mode, we recommend everybody upgrades to Flux v2 and Helm Controller.

A new release of Helm Operator is out this week, 1.4.4.

We will continue to support Helm Operator in maintenance mode for an indefinite period of time, and eventually archive this repository.

Please be aware that Flux v2 has a vibrant and active developer community who are actively working through minor releases and delivering new features on the way to General Availability for Flux v2.

In the mean time, this repo will still be monitored, but support is basically limited to migration issues only. I will have to close many issues today without reading them all in detail because of time constraints. If your issue is very important, you are welcome to reopen it, but due to staleness of all issues at this point a new report is more likely to be in order. Please open another issue if you have unresolved problems that prevent your migration in the appropriate Flux v2 repo.

Helm Operator releases will continue as possible for a limited time, as a courtesy for those who still cannot migrate yet, but these are strongly not recommended for ongoing production use as our strict adherence to semver backward compatibility guarantees limit many dependencies and we can only upgrade them so far without breaking compatibility. So there are likely known CVEs that cannot be resolved.

We recommend upgrading to Flux v2 which is actively maintained ASAP.

I am going to go ahead and close every issue at once today,
Thanks for participating in Helm Operator and Flux! 💚 💙
