### ISSUE TITLE
Helm operator does not notice git changes to child charts

### ISSUE THREAD

**Issue by hiddeco** [fluxcd/helm-operator#16]
In a Helm chart, it is allowed to have relative `file://` references in your `requirements.yaml`, .e.g.:

```
❯ tree charts
charts
├── child/..
└── parent/..

❯ cat charts/parent/requirements.yaml
dependencies:
- name: child
  version: 0.1.0
  repository: file://../child
```

The Helm operator does however [only look for commits touching the configured parent chart path (e.g. `charts/parent`) on git mirror updates](https://github.com/fluxcd/flux/blob/daad1ff216b17db4560d7a154e59cc5b197fd0f2/integrations/helm/chartsync/chartsync.go#L219-L221), which causes changes to child charts to go unnoticed. Subsequent dry-runs do not pick up the change either, as the clone for a `HelmRelease` [is only replaced when a change is detected](https://github.com/fluxcd/flux/blob/daad1ff216b17db4560d7a154e59cc5b197fd0f2/integrations/helm/chartsync/chartsync.go#L240-L242).

The easiest and neatest fix would probably be to always replace the clone of a chart, but to only schedule a release on changes to the parent chart. This would ensure changes to the parent chart result in a priority release, while changes to child charts are still picked up after a while by the sync / mutation prevention mechanism.

**Comment by wgorczyca** [comment]
@hiddeco just to confirm that I understood your solution correctly, we don't need anymore to [check if files in parent chart changed]( https://github.com/fluxcd/helm-operator/blob/e381f7b9e2aad6ee38ee99e6366a7aab80fe8adb/pkg/chartsync/git.go#L270-L278)? instead we assume if head has changed the update is relevant?

**Comment by hiddeco** [comment]
The issue description is no longer accurate for the current behaviour of the Git synchronization and the release process. The files check still needs to be in place as otherwise spurious updates will happen for repositories that contain many charts.

An option would be to read the dependencies of a chart from a Git source by parsing the chart dependency metadata, and add all local dependency paths (`file://`) to the check made [here](https://github.com/fluxcd/helm-operator/blob/master/pkg/release/release.go#L145).

**Comment by cteicher-m** [comment]
What is the intended strategy when a dependency chart is updated. Does `helm dep up` run prior to the dry-run?

**Comment by CarolineTeicher** [comment]
@hiddeco What is the intended strategy when a dependency chart is updated. Does `helm dep up` run prior to the dry-run?

**Comment by kingdonb** [comment]
Sorry if your issue remains unresolved. The Helm Operator is in maintenance mode, we recommend everybody upgrades to Flux v2 and Helm Controller.

A new release of Helm Operator is out this week, 1.4.4.

We will continue to support Helm Operator in maintenance mode for an indefinite period of time, and eventually archive this repository.

Please be aware that Flux v2 has a vibrant and active developer community who are actively working through minor releases and delivering new features on the way to General Availability for Flux v2.

In the mean time, this repo will still be monitored, but support is basically limited to migration issues only. I will have to close many issues today without reading them all in detail because of time constraints. If your issue is very important, you are welcome to reopen it, but due to staleness of all issues at this point a new report is more likely to be in order. Please open another issue if you have unresolved problems that prevent your migration in the appropriate Flux v2 repo.

Helm Operator releases will continue as possible for a limited time, as a courtesy for those who still cannot migrate yet, but these are strongly not recommended for ongoing production use as our strict adherence to semver backward compatibility guarantees limit many dependencies and we can only upgrade them so far without breaking compatibility. So there are likely known CVEs that cannot be resolved.

We recommend upgrading to Flux v2 which is actively maintained ASAP.

I am going to go ahead and close every issue at once today,
Thanks for participating in Helm Operator and Flux! 💚 💙
