### ISSUE TITLE
helm operator fails to progress

### ISSUE THREAD

**Issue by derrickburns** [fluxcd/helm-operator#237]
@hiddeco 

My helmrelease fails because certain resources (service accounts) are missing.  I add the service accounts manually.  However, the helm operator fails to progress.

It seems that the status should not be `pending install` when the Reason is `HelmInstallFailed`.

```
Status:                                                                                                                                                │
│  Conditions:                                                                                                                                          │
│    Last Transition Time:  2020-01-22T00:54:51Z                                                                                                        │
│    Last Update Time:      2020-01-22T06:13:17Z                                                                                                        │
│    Message:               failed to upgrade chart for release [tidepool-loadtest]: release tidepool-loadtest failed, and has been uninstalled due to a│
│tomic being set: timed out waiting for the condition                                                                                                   │
│    Reason:                HelmInstallFailed                                                                                                           │
│    Status:                False                                                                                                                       │
│    Type:                  Released                                                                                                                    │
│  Observed Generation:     3                                                                                                                           │
│  Release Name:            tidepool-loadtest                                                                                                           │
│  Release Status:          pending-install                                                                                                             │
│  Values Checksum:         9d21c098c97c88b5ccc1d6bbd2a10be62ebb73b97652d9db8dcb55c4e87b0948
```

**Additional context**
Add any other context about the problem here, e.g 
- Helm operator version:  helm-operator-prerelease:master-82861733
- Targeted Helm version:
- Kubernetes version:
- Git provider:
- Container registry provider:

**Comment by hiddeco** [comment]
The release status is set by a polling mechanism and is only there for observability, and not to make any decisions around releasing. The `pending-install` in this case is the last recorded status before the release was removed by the initial installation failure (`release tidepool-loadtest failed, and has been uninstalled due to atomic being set`).

From the status I can see that is has attempted multiple times to make the release (difference between the `Last Update Time` and `Last Transition Time`), without making any progress (otherwise the timestamps of the earlier mentioned fields would have been equal to each other).

Are you sure all issues with your chart and/or service accounts have been resolved? It seems to me that the Helm operator just is not able to successfully install the `HelmRelease` with the configured values and given chart.

**Comment by derrickburns** [comment]
I think that I also had an issue with not having enough CPU capacity.  The cluster-autoscaler could not allocate a node. Once I did that, I did see progress.

Thanks.
