### ISSUE TITLE
helm/v3: some error messages are missing formatting and context

### ISSUE THREAD

**Issue by derrickburns** [fluxcd/helm-operator#301]
I am seeing error messages (from rc9) like this one that do not have the new release name and namespace fields.
Can we add them?

```
2020/02/13 21:21:00 warning: cannot overwrite table with non table for policy (map[])
```

**Comment by hiddeco** [comment]
Need a bit more context about the operation being performed before I can say if we are able to add them.

**Comment by derrickburns** [comment]
@hiddeco I do not know what is writing the error message into the helm operator logs.  That is the point. Sorry.

**Comment by derrickburns** [comment]
Here is broader context:
```
│ ts=2020-02-13T21:36:01.763355281Z caller=release.go:360 component=release release=loadtest-mongo targetNamespace=loadtest resource=loadtest:helmrelease/mongo helmVersion=v │
│ ts=2020-02-13T21:36:01.76621114Z caller=helm.go:69 component=helm version=v3 info="preparing upgrade for loadtest-mongo" targetNamespace=loadtest release=loadtest-mongo    │
│ ts=2020-02-13T21:36:01.87882374Z caller=helm.go:69 component=helm version=v3 info="performing update for helm-operator" targetNamespace=flux release=helm-operator          │
│ ts=2020-02-13T21:36:01.892692276Z caller=helm.go:69 component=helm version=v3 info="dry run for helm-operator" targetNamespace=flux release=helm-operator                   │
│ ts=2020-02-13T21:36:01.952093947Z caller=release.go:404 component=release release=helm-operator targetNamespace=flux resource=flux:helmrelease/helm-operator helmVersion=v3 │
│ ts=2020-02-13T21:36:02.097241443Z caller=helm.go:69 component=helm version=v3 info="performing update for loadtest-mongo" targetNamespace=loadtest release=loadtest-mongo   │
│ ts=2020-02-13T21:36:02.111553046Z caller=helm.go:69 component=helm version=v3 info="dry run for loadtest-mongo" targetNamespace=loadtest release=loadtest-mongo             │
│ ts=2020-02-13T21:36:02.122426778Z caller=release.go:404 component=release release=loadtest-mongo targetNamespace=loadtest resource=loadtest:helmrelease/mongo helmVersion=v │
│ ts=2020-02-13T21:36:02.167962402Z caller=release.go:360 component=release release=pomerium targetNamespace=pomerium resource=pomerium:helmrelease/pomerium helmVersion=v3 i │
│ ts=2020-02-13T21:36:02.171669874Z caller=helm.go:69 component=helm version=v3 info="preparing upgrade for pomerium" targetNamespace=pomerium release=pomerium               │
│ ts=2020-02-13T21:36:02.31100937Z caller=release.go:360 component=release release=sumologic-fluentd targetNamespace=sumologic resource=sumologic:helmrelease/sumologic-fluen │
│ ts=2020-02-13T21:36:02.314064008Z caller=helm.go:69 component=helm version=v3 info="preparing upgrade for sumologic-fluentd" targetNamespace=sumologic release=sumologic-fl │
│ 2020/02/13 21:36:02 warning: cannot overwrite table with non table for policy (map[])
```

**Comment by stefansedich** [comment]
I am guessing it is this internal helm log which looks like it uses the logger: https://github.com/helm/helm/blob/9b42702a4bced339ff424a78ad68dd6be6e1a80a/pkg/chartutil/coalesce.go#L196

**Comment by stefansedich** [comment]
Ah actually that is just the standard logger and not the logger we pass into the helm stuff, wonder if we also need to somehow log.SetOutput with a writer that can redirect to our logging func @hiddeco I am guessing that is not done in this case and they are just landing in stdout directly.

**Comment by hiddeco** [comment]
Setting `log.SetOutput` will change it for all processes, we can utilize this so that it prints JSON but adding metadata will be hard.

@stefansedich there is a logger in `pkg/helm` that behaves as an `io.Writer`, that would be the first step to connect it to our own logger. But this still won't add any context to the logged messages.

**Comment by stefansedich** [comment]
@hiddeco yup just realized it is a SetOutput is a global thing, and my logFunc is called every time I want to wrap some context, this one might either be tricky or not possible let me have a think.

**Comment by stefansedich** [comment]
@derrickburns I don't think we can do anything with those logs sadly, I am will make a change so that those log lines get sent through the helm-operator logger so it will respect users settings in regards to json/fmt etc.. but as far as adding context to the log lines helm internally is logging directly with log.Printf there is not alot we can do.

**Comment by derrickburns** [comment]
Perhaps a pr to the helm team to add the necessary interfaces?

**Comment by hiddeco** [comment]
@derrickburns imo, this is much more our problem than their problem.

Looking from Helm’s perspective it makes sense for them to just use `log` there, submitting a PR is an option but it is not directly beneficial to them but only helps people depending on their packages. This makes the chance that it gets rejected substantial and the question is thus if it is worth our efforts.

**Comment by kingdonb** [comment]
Sorry if your issue remains unresolved. The Helm Operator is in maintenance mode, we recommend everybody upgrades to Flux v2 and Helm Controller.

A new release of Helm Operator is out this week, 1.4.4.

We will continue to support Helm Operator in maintenance mode for an indefinite period of time, and eventually archive this repository.

Please be aware that Flux v2 has a vibrant and active developer community who are actively working through minor releases and delivering new features on the way to General Availability for Flux v2.

In the mean time, this repo will still be monitored, but support is basically limited to migration issues only. I will have to close many issues today without reading them all in detail because of time constraints. If your issue is very important, you are welcome to reopen it, but due to staleness of all issues at this point a new report is more likely to be in order. Please open another issue if you have unresolved problems that prevent your migration in the appropriate Flux v2 repo.

Helm Operator releases will continue as possible for a limited time, as a courtesy for those who still cannot migrate yet, but these are strongly not recommended for ongoing production use as our strict adherence to semver backward compatibility guarantees limit many dependencies and we can only upgrade them so far without breaking compatibility. So there are likely known CVEs that cannot be resolved.

We recommend upgrading to Flux v2 which is actively maintained ASAP.

I am going to go ahead and close every issue at once today,
Thanks for participating in Helm Operator and Flux! 💚 💙
