### ISSUE TITLE
Helm chart's default requested resources do not reflect reality

### ISSUE THREAD

**Issue by Gottox** [fluxcd/helm-operator#304]
**Describe the bug**

I'm using the default configuration of the helm-operator deployed with helm. In the [values.yaml](https://github.com/fluxcd/helm-operator/blob/master/chart/helm-operator/values.yaml#L197-L200) the default requests is 64M, but while monitoring the cluster I noticed that the ram size is constantly above 250M. I'm not sure if that is a misconfiguration on my site, but the setup is pretty standard.

I don't manage a lot of charts with the operator either:

```
~ helm list --all-namespaces -q   
database-postgres-operator
flux
get-ip
grafana
helm-operator
kubernetes-dashboard-kubernetes-dashboard
nginx-ingress
postgres-operator
prometheus
```

```
root@tox-worker-01:~# ps -eo rss,comm | grep helm
263668 helm-operator
root@tox-worker-01:~# 
```

**To Reproduce**

Steps to reproduce the behaviour:
1. deploy helm-operator
2. log in to the node running he
3. run `ps -eo rss,comm | grep helm`

**Expected behavior**

A RAM usage that is at least around 64M

**Logs**

If applicable, please provide logs. In a standard stand-alone installation, you'd get this by running `kubectl logs deploy/flux-helm-operator -n fluxcd`.

**Additional context**

- Helm operator version: Chart version: 0.7.0
- Kubernetes version: v1.16.2
- Git provider: 2.25.0

**Comment by runningman84** [comment]
https://github.com/fluxcd/helm-operator/pull/227

**Comment by kingdonb** [comment]
Sorry if your issue remains unresolved. The Helm Operator is in maintenance mode, we recommend everybody upgrades to Flux v2 and Helm Controller.

A new release of Helm Operator is out this week, 1.4.4.

We will continue to support Helm Operator in maintenance mode for an indefinite period of time, and eventually archive this repository.

Please be aware that Flux v2 has a vibrant and active developer community who are actively working through minor releases and delivering new features on the way to General Availability for Flux v2.

In the mean time, this repo will still be monitored, but support is basically limited to migration issues only. I will have to close many issues today without reading them all in detail because of time constraints. If your issue is very important, you are welcome to reopen it, but due to staleness of all issues at this point a new report is more likely to be in order. Please open another issue if you have unresolved problems that prevent your migration in the appropriate Flux v2 repo.

Helm Operator releases will continue as possible for a limited time, as a courtesy for those who still cannot migrate yet, but these are strongly not recommended for ongoing production use as our strict adherence to semver backward compatibility guarantees limit many dependencies and we can only upgrade them so far without breaking compatibility. So there are likely known CVEs that cannot be resolved.

We recommend upgrading to Flux v2 which is actively maintained ASAP.

I am going to go ahead and close every issue at once today,
Thanks for participating in Helm Operator and Flux! 💚 💙
