### ISSUE TITLE
Non destructive update?

### ISSUE THREAD

**Issue by derrickburns** [fluxcd/helm-operator#318]
I need to redeploy a helm chart but I need to leave one deployment and it was replicasets and pods untouched. 

How can I effectively detach those resources from the helm release that created them so that they survive a redeploy of the helm chart?

**Comment by hiddeco** [comment]
Scale the Helm operator down, delete the `HelmRelease` once the pod has disappeared, the release is now unmanaged, scale it up again.

**Comment by derrickburns** [comment]
@hiddeco If I delete the HelmRelease, what will happen to the other resources created by that HelmRelease.  Will they pose a conflict when the Helm Operator tries to apply a replacement HelmRelease?

**Comment by hiddeco** [comment]
If the `HelmRelease` is applied again and the release still exists in the Helm storage, it will attempt an upgrade.

If the release is no longer in the Helm storage, it will attempt an install that will likely fail and result in the removal of the deployment due to the fact that the deployment already exists, during installation failures the operator will perform an uninstall which is resource name based and will delete the resource (this is simply how a Helm uninstall action works).

The only way to work around this is to make sure the new deployment has a different name.

**Comment by derrickburns** [comment]
@hiddeco Thank you!

**Comment by hiddeco** [comment]
If this is all is mission critical, please make sure to test it out somewhere where it does not hurt anyone as due to various reasons and lack of detail in my comments there may be side-effects or things I have not taken into account yet.

**Comment by derrickburns** [comment]
@hiddeco Understood.

**Comment by derrickburns** [comment]
@hiddeco On a separate but related note, I see this:

```
ts=2020-02-26T00:18:14.561935425Z caller=release.go:347 component=release release=tidepool-qa1 targetNamespace=qa1 resource=qa1:helmrelease/tidepool helmVersion=v3 warning="unable to sync release with status pending-upgrade" action=skip
```

I don't understand what is preventing progress.

```
│status:                                                                                                                                                            │
│  conditions:                                                                                                                                                      │
│  - lastTransitionTime: "2020-02-18T02:49:06Z"                                                                                                                     │
│    lastUpdateTime: "2020-02-20T20:50:09Z"                                                                                                                         │
│    message: Helm release sync succeeded                                                                                                                           │
│    reason: HelmSuccess                                                                                                                                            │
│    status: "True"                                                                                                                                                 │
│    type: Released                                                                                                                                                 │
│  - lastTransitionTime: "2020-02-25T23:51:21Z"                                                                                                                     │
│    lastUpdateTime: "2020-02-26T00:21:12Z"                                                                                                                         │
│    message: 'successfully cloned chart revision: 38c2a64498982df1e0d30bc09b26c81f2bdd31be'                                                                        │
│    reason: GitRepoCloned                                                                                                                                          │
│    status: "True"                                                                                                                                                 │
│    type: ChartFetched                                                                                                                                             │
│  observedGeneration: 32                                                                                                                                           │
│  releaseName: tidepool-qa1                                                                                                                                        │
│  releaseStatus: pending-upgrade                                                                                                                                   │
│  revision: 38c2a64498982df1e0d30bc09b26c81f2bdd31be
```

```
  Rollback:                                                                                                                                                        │
│    Enable:       true                                                                                                                                             │
│    Force:        true                                                                                                                                             │
│    Max Retries:  0                                                                                                                                                │
│    Retry:        true
```

Can you enlighten me?

**Comment by hiddeco** [comment]
One thing I can think of is that the Helm operator pod was deleted while performing a release for this Helm release and the default `terminationGracePeriodSeconds` of `30s` wasn’t sufficient for the long running upgrade to finish cleanly before the pod got force killed.

You can recover from this state by performing a manual release.

In addition, we should probably make the `terminationGracePeriodSeconds` configurable in the chart and add a note to the `Deployment` in `deploy/` that this value may need some tweaking.

**Comment by derrickburns** [comment]
Ah.  Thank you!

**Comment by derrickburns** [comment]
I had to do a rollback and then a release.

**Comment by kingdonb** [comment]
Sorry if your issue remains unresolved. The Helm Operator is in maintenance mode, we recommend everybody upgrades to Flux v2 and Helm Controller.

A new release of Helm Operator is out this week, 1.4.4.

We will continue to support Helm Operator in maintenance mode for an indefinite period of time, and eventually archive this repository.

Please be aware that Flux v2 has a vibrant and active developer community who are actively working through minor releases and delivering new features on the way to General Availability for Flux v2.

In the mean time, this repo will still be monitored, but support is basically limited to migration issues only. I will have to close many issues today without reading them all in detail because of time constraints. If your issue is very important, you are welcome to reopen it, but due to staleness of all issues at this point a new report is more likely to be in order. Please open another issue if you have unresolved problems that prevent your migration in the appropriate Flux v2 repo.

Helm Operator releases will continue as possible for a limited time, as a courtesy for those who still cannot migrate yet, but these are strongly not recommended for ongoing production use as our strict adherence to semver backward compatibility guarantees limit many dependencies and we can only upgrade them so far without breaking compatibility. So there are likely known CVEs that cannot be resolved.

We recommend upgrading to Flux v2 which is actively maintained ASAP.

I am going to go ahead and close every issue at once today,
Thanks for participating in Helm Operator and Flux! 💚 💙
