### ISSUE TITLE
Renaming crds.yaml breaks installation documentation

### ISSUE THREAD

**Issue by ConnorBarnhill** [fluxcd/helm-operator#323]
Because the docs (https://docs.fluxcd.io/en/stable/tutorials/get-started-helm.html) reference raw files in the master branch, the stable docs are now broken when trying to install `kubectl apply -f https://raw.githubusercontent.com/fluxcd/helm-operator/master/deploy/flux-helm-release-crd.yaml`

**Comment by hiddeco** [comment]
The documentation you are referring to is Flux, and not the Helm operator. This issue would thus belong in the Flux repository.

In addition, looking back, we should not have used a link to `master` there but a pinned version. Holding back changes to `master` here because of this reference is not doable as this would mean we can never make any progress here. The URL has been fixed for the `lastest` documentation, and I will make sure it references to a tagged version for the next Flux release.
