### ISSUE TITLE
`go get github.com/fluxcd/helm-operator` fails

### ISSUE THREAD

**Issue by limscoder** [fluxcd/helm-operator#336]
**Describe the bug**
`go get` fails with go 1.13

**To Reproduce**

```bash
go get github.com/fluxcd/helm-operator
go: github.com/fluxcd/helm-operator upgrade => v1.0.0-rc9
go get: github.com/fluxcd/helm-operator@v1.0.0-rc9 requires
	github.com/fluxcd/helm-operator/pkg/install@v0.0.0-00010101000000-000000000000: invalid version: unknown revision 000000000000
```

**Expected behavior**

Module is installed

**Comment by hiddeco** [comment]
This is due to a circular dependency with `github.com/fluxcd/flux` due to re-using the `git` and `resource` packages from there, while Flux also depends on a version of `fluxcd/helm-operator` (all of this mostly due to the Helm operator originating from a monolith).

The solution (for now) is to force overwrite the version using a `replace`:

```
# go.mod
replace github.com/fluxcd/helm-operator => github.com/fluxcd/helm-operator v1.0.0-rc9
```

**Comment by grahamhayes** [comment]
This doesn't seem to fix it for me - I still get the same error with the replace line in my go.mod file.

**Comment by sayboras** [comment]
I got below replace in my go.mod, you can give it a try

```
replace (
	github.com/docker/distribution => github.com/docker/distribution v0.0.0-20191216044856-a8371794149d
	github.com/docker/docker => github.com/moby/moby v1.4.2-0.20200203170920-46ec8731fbce
	github.com/fluxcd/flux => github.com/fluxcd/flux v1.19.0
	github.com/fluxcd/flux/pkg/install => github.com/fluxcd/flux/pkg/install v0.0.0-20200402061723-01a239a69319
	github.com/fluxcd/helm-operator/pkg/install => github.com/fluxcd/helm-operator/pkg/install v0.0.0-20200407140510-8d71b0072a3e
)
```

**Comment by grahamhayes** [comment]
```
•100% ➜ go get github.com/fluxcd/helm-operator
go: github.com/fluxcd/helm-operator upgrade => v1.0.1
can't load package: package github.com/fluxcd/helm-operator: build constraints exclude all Go files in /Users/grhayes/go/pkg/mod/github.com/fluxcd/helm-operator@v1.0.1
```
My `go.mod` file:

```
module grahamhayes/test

go 1.14

replace (
	github.com/docker/distribution => github.com/docker/distribution v0.0.0-20191216044856-a8371794149d
	github.com/docker/docker => github.com/moby/moby v1.4.2-0.20200203170920-46ec8731fbce
	github.com/fluxcd/flux => github.com/fluxcd/flux v1.19.0
	github.com/fluxcd/flux/pkg/install => github.com/fluxcd/flux/pkg/install v0.0.0-20200402061723-01a239a69319
	github.com/fluxcd/helm-operator/pkg/install => github.com/fluxcd/helm-operator/pkg/install v0.0.0-20200407140510-8d71b0072a3e
)

require github.com/fluxcd/helm-operator v1.0.1 // indirect
```

**Comment by kingdonb** [comment]
Sorry if your issue remains unresolved. The Helm Operator is in maintenance mode, we recommend everybody upgrades to Flux v2 and Helm Controller.

A new release of Helm Operator is out this week, 1.4.4.

We will continue to support Helm Operator in maintenance mode for an indefinite period of time, and eventually archive this repository.

Please be aware that Flux v2 has a vibrant and active developer community who are actively working through minor releases and delivering new features on the way to General Availability for Flux v2.

In the mean time, this repo will still be monitored, but support is basically limited to migration issues only. I will have to close many issues today without reading them all in detail because of time constraints. If your issue is very important, you are welcome to reopen it, but due to staleness of all issues at this point a new report is more likely to be in order. Please open another issue if you have unresolved problems that prevent your migration in the appropriate Flux v2 repo.

Helm Operator releases will continue as possible for a limited time, as a courtesy for those who still cannot migrate yet, but these are strongly not recommended for ongoing production use as our strict adherence to semver backward compatibility guarantees limit many dependencies and we can only upgrade them so far without breaking compatibility. So there are likely known CVEs that cannot be resolved.

We recommend upgrading to Flux v2 which is actively maintained ASAP.

I am going to go ahead and close every issue at once today,
Thanks for participating in Helm Operator and Flux! 💚 💙
