### ISSUE TITLE
Microservices best practices

### ISSUE THREAD

**Issue by ghost** [fluxcd/helm-operator#38]
I have an architectural question regarding flux and helm. I'm following the https://github.com/fluxcd/helm-operator-get-started/ tutorial.

In my project, I have tens of microservices which can not live without each other. What would be your suggestion? Should I create as many charts and HelmReleases as many microservice I have, or just create a generic chart, which contains all of the microservices helm yaml files (like deployment, service, etc...)?

**Comment by terrafying** [comment]
Looks like this has been unanswered for over a year, so I'll add my thoughts...  We have 20-30 microservices which are mostly identical, but require slightly different ingress rules, environment variables, configuration files, etc - and across many different environments (integration, QA, production, and some extra ones).  I went with a single generic helm chart, with multiple HelmReleases which specify a different container image, env vars, ingress spec, etc.  This is relatively less copypaste, and easier to update than a bunch of nearly-identical helm charts.  If there is a strict order, you can use initContainers in your deployments to await the existence of the required services.  Otherwise, there isn't a dependency order achievable in flux as far as I know.

**Comment by kingdonb** [comment]
Sorry if your issue remains unresolved. The Helm Operator is in maintenance mode, we recommend everybody upgrades to Flux v2 and Helm Controller.

A new release of Helm Operator is out this week, 1.4.4.

We will continue to support Helm Operator in maintenance mode for an indefinite period of time, and eventually archive this repository.

Please be aware that Flux v2 has a vibrant and active developer community who are actively working through minor releases and delivering new features on the way to General Availability for Flux v2.

In the mean time, this repo will still be monitored, but support is basically limited to migration issues only. I will have to close many issues today without reading them all in detail because of time constraints. If your issue is very important, you are welcome to reopen it, but due to staleness of all issues at this point a new report is more likely to be in order. Please open another issue if you have unresolved problems that prevent your migration in the appropriate Flux v2 repo.

Helm Operator releases will continue as possible for a limited time, as a courtesy for those who still cannot migrate yet, but these are strongly not recommended for ongoing production use as our strict adherence to semver backward compatibility guarantees limit many dependencies and we can only upgrade them so far without breaking compatibility. So there are likely known CVEs that cannot be resolved.

We recommend upgrading to Flux v2 which is actively maintained ASAP.

I am going to go ahead and close every issue at once today,
Thanks for participating in Helm Operator and Flux! 💚 💙
