### ISSUE TITLE
Automated rollback based on condition 

### ISSUE THREAD

**Issue by singh-brajesh247** [fluxcd/helm-operator#380]
**Can helm-operator handle automated rollback based on some condition**
   1. Based on liveness and readiness probs 
       If liveness or readyness failed HelmRelease should rollback to the last successful revision. 
   2. Based on some dependency.
       During the deployment helm-operator should check the other HelmRelease deployed successfully.
 
**Here is my configuration that i am using**
     apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: prod-release
  namespace: prod

spec:
  releaseName: prod-release
  helmVersion: v3
  #targetNamespace: default
  timeout: 300
  #resetValues: false
  wait: true
  #forceUpgrade: false
  chart:
    git: git@bitbucket.org:example/fluxcd.git
    path: charts/example
    ref: master
  values:
    image:
      repository: nginx
      tag: latest
    replicaCount: 2

  rollback:
    enable: true
    wait: true
    force: false
    disableHooks: true
    timeout: 300

**Comment by hiddeco** [comment]
> If liveness or readyness failed HelmRelease should rollback to the last successful revision.

This should already be covered by setting `rollback.true` and `rollback.wait`, as the `wait` causes the operator to upgrade with `--wait`, and this should fail when any of the liveness of readiness probes do not reach their expected state within time.

I am however aware there may be some edge cases where this does not work, this should however be fixed at the Helm side and not by us implementing additional logic on top of this.

> During the deployment helm-operator should check the other HelmRelease deployed successfully.

Is this about a `HelmRelease` depending on the presence of another `HelmRelease`? If so, this has been requested multiple times but I am still of opinion this should be resolved within charts themselves (by e.g. checking it the port of a service is reachable before booting starting the actual application container, as this will make the release fail if it is unreachable and the rollback should kick in).

The only place where I think such a feature could be implemented is during installations (see #362), for example because those dependent `HelmRelease` resources install `CustomResourceDefinition` resources that are utilized by other charts.

**Comment by singh-brajesh247** [comment]
@hiddeco: Thanks for you reply. 
Is this feature available into helm v3 and helm v2. Actually, i am running 4 container into a pod and i have enabled liveness and readiness but during deployment - when readiness or liveness show unhealthy helm-operator marked as ready and  deployed. 

Also, you mentioned edge cases : What is mean ?

**Comment by kingdonb** [comment]
Sorry if your issue remains unresolved. The Helm Operator is in maintenance mode, we recommend everybody upgrades to Flux v2 and Helm Controller.

A new release of Helm Operator is out this week, 1.4.4.

We will continue to support Helm Operator in maintenance mode for an indefinite period of time, and eventually archive this repository.

Please be aware that Flux v2 has a vibrant and active developer community who are actively working through minor releases and delivering new features on the way to General Availability for Flux v2.

In the mean time, this repo will still be monitored, but support is basically limited to migration issues only. I will have to close many issues today without reading them all in detail because of time constraints. If your issue is very important, you are welcome to reopen it, but due to staleness of all issues at this point a new report is more likely to be in order. Please open another issue if you have unresolved problems that prevent your migration in the appropriate Flux v2 repo.

Helm Operator releases will continue as possible for a limited time, as a courtesy for those who still cannot migrate yet, but these are strongly not recommended for ongoing production use as our strict adherence to semver backward compatibility guarantees limit many dependencies and we can only upgrade them so far without breaking compatibility. So there are likely known CVEs that cannot be resolved.

We recommend upgrading to Flux v2 which is actively maintained ASAP.

I am going to go ahead and close every issue at once today,
Thanks for participating in Helm Operator and Flux! 💚 💙
