### ISSUE TITLE
Port Kubernetes client-go 1.18 and helm 3.2.0.

### ISSUE THREAD

**Issue by swade1987** [fluxcd/helm-operator#391]
**Describe the feature**
We should be using Helm 3.2.0 due to the CVE in Helm 3.1.x releases.
As part of Helm 3.2.0 it requires the use of client-go 1.18

**What would the new user story look like?**
A new Helm Operator version being cut.

**Comment by wmgroot** [comment]
Appreciate it! Helm 3.2.0 also contains a preventative fix for https://github.com/helm/helm/issues/5595, which is currently affecting users in my clusters.

**Comment by acobaugh** [comment]
Should probably use helm 3.2.1 to include https://github.com/helm/helm/pull/7653, which will let us recover from a failed release in some cases by updating the chart version.

**Comment by acobaugh** [comment]
Just to add one more point in favor of updating to helm 3.2.x, the issue that this PR fixes has found us dead in the water multiple times as we upgrade HelmReleases that upgrade the api version of resources (Ingress went from `extensions/v1beta1` to `networking.k8s.io/v1`): https://github.com/helm/helm/pull/7649

Would PRs be welcome for this work?

**Comment by stefanprodan** [comment]
Upgrading the helm libraries in not that easy since they come with Kubernetes client-go 1.18 and that comes with breaking changes and we need to change all API calls in helm-controller. The helm v2 libraries haven't been upgraded to Kubernetes 1.18 so if we make helm-operator work with v3 libs and client-go 1.18, we will probably break v2.

**Comment by stefansedich** [comment]
+1 on this, we have some changes we need to push out changing apiVersions and would save some effort.

**Comment by caruccio** [comment]
Also, 3.2 adds support for more functions, like `htpasswd`

**Comment by kingdonb** [comment]
Sorry if your issue remains unresolved. The Helm Operator is in maintenance mode, we recommend everybody upgrades to Flux v2 and Helm Controller.

A new release of Helm Operator is out this week, 1.4.4.

We will continue to support Helm Operator in maintenance mode for an indefinite period of time, and eventually archive this repository.

Please be aware that Flux v2 has a vibrant and active developer community who are actively working through minor releases and delivering new features on the way to General Availability for Flux v2.

In the mean time, this repo will still be monitored, but support is basically limited to migration issues only. I will have to close many issues today without reading them all in detail because of time constraints. If your issue is very important, you are welcome to reopen it, but due to staleness of all issues at this point a new report is more likely to be in order. Please open another issue if you have unresolved problems that prevent your migration in the appropriate Flux v2 repo.

Helm Operator releases will continue as possible for a limited time, as a courtesy for those who still cannot migrate yet, but these are strongly not recommended for ongoing production use as our strict adherence to semver backward compatibility guarantees limit many dependencies and we can only upgrade them so far without breaking compatibility. So there are likely known CVEs that cannot be resolved.

We recommend upgrading to Flux v2 which is actively maintained ASAP.

I am going to go ahead and close every issue at once today,
Thanks for participating in Helm Operator and Flux! 💚 💙
