### ISSUE TITLE
Deprecate status "phases"

### ISSUE THREAD

**Issue by seaneagan** [fluxcd/helm-operator#404]
**Describe the feature**

Release status phases, which were exposed in #334 are now a [deprecated concept](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#typical-status-properties) in the kubernetes API conventions. There is [ongoing work](https://github.com/kubernetes/enhancements/pull/1624) on these conventions, but in general status conditions appear to be the path forward. These steps could be taken to move away from phases towards conditions:

1. See #395 
2. See #406
3. Reframe phases as `HelmReleaseConditionReason`s (or possibly `HelmReleaseEvent` if there is a desire to expose as kubernetes events as well) in the code base
4. remove `status.phase` (has to wait for HelmRelease v2?)

**Comment by seaneagan** [comment]
3. should follow how it's done in the other toolkit components:

https://github.com/fluxcd/source-controller/blob/b078847ce8c87a412c5798fc32faabcc2d7eb58c/api/v1alpha1/condition_types.go#L55
https://github.com/fluxcd/kustomize-controller/blob/81e077811f3ed09275a8eb5a063fd8c3b61e6bc1/api/v1alpha1/condition_types.go#L56

**Comment by kingdonb** [comment]
Sorry if your issue remains unresolved. The Helm Operator is in maintenance mode, we recommend everybody upgrades to Flux v2 and Helm Controller.

A new release of Helm Operator is out this week, 1.4.4.

We will continue to support Helm Operator in maintenance mode for an indefinite period of time, and eventually archive this repository.

Please be aware that Flux v2 has a vibrant and active developer community who are actively working through minor releases and delivering new features on the way to General Availability for Flux v2.

In the mean time, this repo will still be monitored, but support is basically limited to migration issues only. I will have to close many issues today without reading them all in detail because of time constraints. If your issue is very important, you are welcome to reopen it, but due to staleness of all issues at this point a new report is more likely to be in order. Please open another issue if you have unresolved problems that prevent your migration in the appropriate Flux v2 repo.

Helm Operator releases will continue as possible for a limited time, as a courtesy for those who still cannot migrate yet, but these are strongly not recommended for ongoing production use as our strict adherence to semver backward compatibility guarantees limit many dependencies and we can only upgrade them so far without breaking compatibility. So there are likely known CVEs that cannot be resolved.

We recommend upgrading to Flux v2 which is actively maintained ASAP.

I am going to go ahead and close every issue at once today,
Thanks for participating in Helm Operator and Flux! 💚 💙
