### ISSUE TITLE
Not able to run heml3 upgrade

### ISSUE THREAD

**Issue by mohsinniveus** [fluxcd/helm-operator#432]
Hi I am trying to install flux-get-started project using helm chart. 

Blow is command
helm3 upgrade -i flux fluxcd/flux \
   --set git.url=git@github.com:mohsinniveus/flux-get-started \
   --namespace flux

Below is command line logs

Error: UPGRADE FAILED: query: failed to query with labels: <html><head><meta http-equiv='refresh' content='1;url=/login?from=%2Fapi%2Fv1%2Fnamespaces%2Fflux%2Fsecrets%3FlabelSelector%3Dname%253Dhelm-operator%252Cowner%253Dhelm%252Cstatus%253Ddeployed'/><script>window.location.replace('/login?from=%2Fapi%2Fv1%2Fnamespaces%2Fflux%2Fsecrets%3FlabelSelector%3Dname%253Dhelm-operator%252Cowner%253Dhelm%252Cstatus%253Ddeployed');</script></head><body style='background-color:white; color:white;'>

Authentication required

minikube version: v1.10.1
commit: 63ab801ac27e5742ae442ce36dff7877dcccb278

version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}

**Comment by kingdonb** [comment]
Sorry if your issue remains unresolved. The Helm Operator is in maintenance mode, we recommend everybody upgrades to Flux v2 and Helm Controller.

A new release of Helm Operator is out this week, 1.4.4.

We will continue to support Helm Operator in maintenance mode for an indefinite period of time, and eventually archive this repository.

Please be aware that Flux v2 has a vibrant and active developer community who are actively working through minor releases and delivering new features on the way to General Availability for Flux v2.

In the mean time, this repo will still be monitored, but support is basically limited to migration issues only. I will have to close many issues today without reading them all in detail because of time constraints. If your issue is very important, you are welcome to reopen it, but due to staleness of all issues at this point a new report is more likely to be in order. Please open another issue if you have unresolved problems that prevent your migration in the appropriate Flux v2 repo.

Helm Operator releases will continue as possible for a limited time, as a courtesy for those who still cannot migrate yet, but these are strongly not recommended for ongoing production use as our strict adherence to semver backward compatibility guarantees limit many dependencies and we can only upgrade them so far without breaking compatibility. So there are likely known CVEs that cannot be resolved.

We recommend upgrading to Flux v2 which is actively maintained ASAP.

I am going to go ahead and close every issue at once today,
Thanks for participating in Helm Operator and Flux! 💚 💙
