### ISSUE TITLE
frequent "no API version specified" errors since switching to library charts

### ISSUE THREAD

**Issue by languitar** [fluxcd/helm-operator#446]
**Describe the bug**
A few days ago we have introduced a library chart for our privately maintained charts. The library chart is part of a mono-repo that also includes all component charts. Since deploying the new component chart versions depending on the library charts, the helm operator in our cluster frequently reports such errors for random components:
```
ts=2020-06-04T14:19:46.987755263Z caller=release.go:81 component=release release=gdprlog targetNamespace=planone resource=planone:helmrelease/gdprlog helmVersion=v3 error="failed to prepare chart for release: no API version specified"
```
The components are correctly deployed and updated by the operator and these seem to be transient errors. However, their source remains unclear to us.

**Expected behavior**
These errors shouldn't be logged.

**Logs**
```
ts=2020-06-04T12:25:32.848146653Z caller=logwriter.go:28 component=helm version=v3 info="Hang tight while we grab the latest from your chart repositories..."
ts=2020-06-04T12:25:32.865476732Z caller=logwriter.go:28 component=helm version=v3 info="...Successfully got an update from the \"external-secrets\" chart repository"
ts=2020-06-04T12:25:32.866361636Z caller=logwriter.go:28 component=helm version=v3 info="...Successfully got an update from the \"external-auth-server\" chart repository"
ts=2020-06-04T12:25:32.889221462Z caller=logwriter.go:28 component=helm version=v3 info="...Successfully got an update from the \"codecentric\" chart repository"
ts=2020-06-04T12:25:32.891229245Z caller=logwriter.go:28 component=helm version=v3 info="...Successfully got an update from the \"YYY\" chart repository"
ts=2020-06-04T12:25:32.900609378Z caller=logwriter.go:28 component=helm version=v3 info="...Successfully got an update from the \"fluxcd\" chart repository"
ts=2020-06-04T12:25:32.939076177Z caller=logwriter.go:28 component=helm version=v3 info="...Successfully got an update from the \"maesh\" chart repository"
ts=2020-06-04T12:25:32.942955413Z caller=logwriter.go:28 component=helm version=v3 info="...Successfully got an update from the \"jetstack\" chart repository"
ts=2020-06-04T12:25:37.507248989Z caller=logwriter.go:28 component=helm version=v3 info="...Successfully got an update from the \"stable\" chart repository"
ts=2020-06-04T12:25:37.507329548Z caller=logwriter.go:28 component=helm version=v3 info="Update Complete. ⎈Happy Helming!⎈"
ts=2020-06-04T12:25:37.588098875Z caller=logwriter.go:28 component=helm version=v3 info="...Successfully got an update from the \"stable\" chart repository"
ts=2020-06-04T12:25:37.588169723Z caller=logwriter.go:28 component=helm version=v3 info="Update Complete. ⎈Happy Helming!⎈"
ts=2020-06-04T12:25:37.614265263Z caller=release.go:81 component=release release=airflow-inlet targetNamespace=XXX resource=XXX:helmrelease/airflow-inlet helmVersion=v3 error="failed to prepare chart for release: no API version specified"
ts=2020-06-04T12:25:37.615530573Z caller=release.go:75 component=release release=grafana targetNamespace=XXX-monitoring resource=XXX-monitoring:helmrelease/grafana helmVersion=v3 info="starting sync run"
ts=2020-06-04T12:25:38.39896785Z caller=release.go:249 component=release release=grafana targetNamespace=XXX-monitoring resource=XXX-monitoring:helmrelease/grafana helmVersion=v3 info="running dry-run upgrade to compare with release version '7'" action=dry-run-compare
ts=2020-06-04T12:25:38.406215872Z caller=helm.go:69 component=helm version=v3 info="preparing upgrade for grafana" targetNamespace=XXX-monitoring release=grafana
```

**Additional context**
Add any other context about the problem here, e.g 
- Helm Operator version: helm-operator:1.0.1
- Targeted Helm version: 3.2.0
- Kubernetes version: v1.16.8-eks-e16311
- Git provider: gitlab
- Container registry provider: gitlab and dockerhub

**Comment by davidbalazs** [comment]
we are encountering the same issue now with helm-operator:1.0.1 and helm 3.2.0 (we need to keep using this version until this issue is fixed: https://github.com/fluxcd/helm-operator/issues/457

**Comment by kingdonb** [comment]
Sorry if your issue remains unresolved. The Helm Operator is in maintenance mode, we recommend everybody upgrades to Flux v2 and Helm Controller.

A new release of Helm Operator is out this week, 1.4.4.

We will continue to support Helm Operator in maintenance mode for an indefinite period of time, and eventually archive this repository.

Please be aware that Flux v2 has a vibrant and active developer community who are actively working through minor releases and delivering new features on the way to General Availability for Flux v2.

In the mean time, this repo will still be monitored, but support is basically limited to migration issues only. I will have to close many issues today without reading them all in detail because of time constraints. If your issue is very important, you are welcome to reopen it, but due to staleness of all issues at this point a new report is more likely to be in order. Please open another issue if you have unresolved problems that prevent your migration in the appropriate Flux v2 repo.

Helm Operator releases will continue as possible for a limited time, as a courtesy for those who still cannot migrate yet, but these are strongly not recommended for ongoing production use as our strict adherence to semver backward compatibility guarantees limit many dependencies and we can only upgrade them so far without breaking compatibility. So there are likely known CVEs that cannot be resolved.

We recommend upgrading to Flux v2 which is actively maintained ASAP.

I am going to go ahead and close every issue at once today,
Thanks for participating in Helm Operator and Flux! 💚 💙
