### ISSUE TITLE
Reset rollback count upon new desired release state

### ISSUE THREAD

**Issue by seaneagan** [fluxcd/helm-operator#447]
**Describe the bug**

Currently the rollback count only gets reset upon a successful upgrade. So if one state is upgraded/rolled back a number of times without success, and the release is patched with a fix, the new state only gets the remaining retries to succeed. In the case where the max retries were already reached, only one attempt is given. It seems each state should get the full configured amount of retries to succeed, regardless of what happened with a prior state.

**Additional context**

- Helm Operator version: 1.1.0
- Kubernetes version:
- Git provider:
- Helm repository provider:

**Comment by kingdonb** [comment]
Sorry if your issue remains unresolved. The Helm Operator is in maintenance mode, we recommend everybody upgrades to Flux v2 and Helm Controller.

A new release of Helm Operator is out this week, 1.4.4.

We will continue to support Helm Operator in maintenance mode for an indefinite period of time, and eventually archive this repository.

Please be aware that Flux v2 has a vibrant and active developer community who are actively working through minor releases and delivering new features on the way to General Availability for Flux v2.

In the mean time, this repo will still be monitored, but support is basically limited to migration issues only. I will have to close many issues today without reading them all in detail because of time constraints. If your issue is very important, you are welcome to reopen it, but due to staleness of all issues at this point a new report is more likely to be in order. Please open another issue if you have unresolved problems that prevent your migration in the appropriate Flux v2 repo.

Helm Operator releases will continue as possible for a limited time, as a courtesy for those who still cannot migrate yet, but these are strongly not recommended for ongoing production use as our strict adherence to semver backward compatibility guarantees limit many dependencies and we can only upgrade them so far without breaking compatibility. So there are likely known CVEs that cannot be resolved.

We recommend upgrading to Flux v2 which is actively maintained ASAP.

I am going to go ahead and close every issue at once today,
Thanks for participating in Helm Operator and Flux! 💚 💙
