### ISSUE TITLE
Occasional helm test runs after deployment

### ISSUE THREAD

**Issue by seaneagan** [fluxcd/helm-operator#452]
As an extension to #369, it may be useful to occasionally run helm tests on a deployed release, both on demand and periodically:

1. Add `helm.fluxcd.io/testAt: <timestamp>` annotation, similar to #453, except only triggers tests, not a full sync.
2. Add `spec.test.interval` field which would cause the helm tests to be re-run if they haven't been run within the interval.

Unclear if these tests should result in uninstalls/rollbacks/retries. Probably not by default, maybe useful though as configuration option.

**Comment by hiddeco** [comment]
If we opt to introduce `helm.fluxcd.io/testAt` (for which you got my vote), we should introduce `helm.fluxcd.io/syncAt` as well to clear the path for #444.

**Comment by hiddeco** [comment]
Ah, I had not seen #453 yet. :ok_hand:

**Comment by hiddeco** [comment]
One thing that is up for debate, given the behaviour introduced in #369, is the rollback. I am not sure that if you run tests periodically to assert everything is (still) working as expected, you want a rollback to happen if it fails several days after the actual release was made.

**Comment by seaneagan** [comment]
:+1: , added #454 for configuration of rollbacks/uninstalls on test failures

**Comment by gmtstephane** [comment]
Hi, what about the initial message ?
Will it be possible to trigger test on a specific release ?
Or to configure a test to run every X minutes ?

Thanks

**Comment by kingdonb** [comment]
Sorry if your issue remains unresolved. The Helm Operator is in maintenance mode, we recommend everybody upgrades to Flux v2 and Helm Controller.

A new release of Helm Operator is out this week, 1.4.4.

We will continue to support Helm Operator in maintenance mode for an indefinite period of time, and eventually archive this repository.

Please be aware that Flux v2 has a vibrant and active developer community who are actively working through minor releases and delivering new features on the way to General Availability for Flux v2.

In the mean time, this repo will still be monitored, but support is basically limited to migration issues only. I will have to close many issues today without reading them all in detail because of time constraints. If your issue is very important, you are welcome to reopen it, but due to staleness of all issues at this point a new report is more likely to be in order. Please open another issue if you have unresolved problems that prevent your migration in the appropriate Flux v2 repo.

Helm Operator releases will continue as possible for a limited time, as a courtesy for those who still cannot migrate yet, but these are strongly not recommended for ongoing production use as our strict adherence to semver backward compatibility guarantees limit many dependencies and we can only upgrade them so far without breaking compatibility. So there are likely known CVEs that cannot be resolved.

We recommend upgrading to Flux v2 which is actively maintained ASAP.

I am going to go ahead and close every issue at once today,
Thanks for participating in Helm Operator and Flux! 💚 💙
