### ISSUE TITLE
Annotation to force HelmRelease upgrade

### ISSUE THREAD

**Issue by seaneagan** [fluxcd/helm-operator#453]
There are times where the dry run compare is not smart enough to pickup all changes. Currently the workaround is that upgrades occur on each new HelmRelease generation, so updates can be forced by updating the generation. However, there are couple issues with this:

1. Leads to unnecessary upgrade, see #444 
2. It's not clear which field should be updated, since `metadata` changes don't result in a new generation?

Proposal:

1. Add a `helm.fluxcd.io/syncAt: <timestamp>` annotation, similar to [this one](https://github.com/fluxcd/source-controller/blob/b078847ce8c87a412c5798fc32faabcc2d7eb58c/docs/spec/v1alpha1/common.md#source-synchronization). See also #452

**Comment by hiddeco** [comment]
> which forces the release to be upgraded if it hasn't been since the timestamp.

The way the source controller which you linked to as an inspiration works at the moment, is that the value of the annotation does not really matter. What actually triggers a synchronization is the value of the annotation deferring from the old value. The reason timestamps are used is because they provide an easy way to generate a unique value on each run which differs from the previous value, but the time itself isn't taken into account.

**Comment by seaneagan** [comment]
That makese sense, since time coordination between between client and server may not be reliable.

**Comment by seaneagan** [comment]
Also updated the proposal to use `syncAt` after all since the whole sync process is triggered (including tests if enabled).

**Comment by hiddeco** [comment]
:+1:, are you by any chance active in one of the many "Kubernetes Slack communities" (K8S, CNCF, Weave Community, etc)? Would love to have a chat with you given the amount of contributions lately.

**Comment by kingdonb** [comment]
Sorry if your issue remains unresolved. The Helm Operator is in maintenance mode, we recommend everybody upgrades to Flux v2 and Helm Controller.

A new release of Helm Operator is out this week, 1.4.4.

We will continue to support Helm Operator in maintenance mode for an indefinite period of time, and eventually archive this repository.

Please be aware that Flux v2 has a vibrant and active developer community who are actively working through minor releases and delivering new features on the way to General Availability for Flux v2.

In the mean time, this repo will still be monitored, but support is basically limited to migration issues only. I will have to close many issues today without reading them all in detail because of time constraints. If your issue is very important, you are welcome to reopen it, but due to staleness of all issues at this point a new report is more likely to be in order. Please open another issue if you have unresolved problems that prevent your migration in the appropriate Flux v2 repo.

Helm Operator releases will continue as possible for a limited time, as a courtesy for those who still cannot migrate yet, but these are strongly not recommended for ongoing production use as our strict adherence to semver backward compatibility guarantees limit many dependencies and we can only upgrade them so far without breaking compatibility. So there are likely known CVEs that cannot be resolved.

We recommend upgrading to Flux v2 which is actively maintained ASAP.

I am going to go ahead and close every issue at once today,
Thanks for participating in Helm Operator and Flux! 💚 💙
