### ISSUE TITLE
Document relevance of --enabled-helm-versions order

### ISSUE THREAD

**Issue by rndstr** [fluxcd/helm-operator#466]
The order of versions in `--enabled-helm-versions=v2,v3` determines the default value (first is default) if the HelmRelease does not specify a version itself. I could not find this mentioned in the [documentation](https://docs.fluxcd.io/projects/helm-operator/en/latest/references/operator/#helm-configuration) and I think it should be added.

### Details
While reviewing #462 we came across `Release#config.DefaultHelmVersion` which is used as argument for most (all?) calls to [`HelmRelease#GetHelmVersion()`](https://github.com/fluxcd/helm-operator/blob/f3d937cd6323e345be444b9cc14f6878d5cb81ff/pkg/apis/helm.fluxcd.io/v1/types_helmrelease.go#L85)

`Release#config.DefaultHelmVersion` is being set through
https://github.com/fluxcd/helm-operator/blob/f3d937cd6323e345be444b9cc14f6878d5cb81ff/cmd/helm-operator/main.go#L205-L232
by
https://github.com/fluxcd/helm-operator/blob/f3d937cd6323e345be444b9cc14f6878d5cb81ff/cmd/helm-operator/main.go#L275

Hence. the flag `--enabled-helm-versions=v3,v2` has not the same behavior as `--enabled-helm-versions=v2,v3`

**Comment by kingdonb** [comment]
Sorry if your issue remains unresolved. The Helm Operator is in maintenance mode, we recommend everybody upgrades to Flux v2 and Helm Controller.

A new release of Helm Operator is out this week, 1.4.4.

We will continue to support Helm Operator in maintenance mode for an indefinite period of time, and eventually archive this repository.

Please be aware that Flux v2 has a vibrant and active developer community who are actively working through minor releases and delivering new features on the way to General Availability for Flux v2.

In the mean time, this repo will still be monitored, but support is basically limited to migration issues only. I will have to close many issues today without reading them all in detail because of time constraints. If your issue is very important, you are welcome to reopen it, but due to staleness of all issues at this point a new report is more likely to be in order. Please open another issue if you have unresolved problems that prevent your migration in the appropriate Flux v2 repo.

Helm Operator releases will continue as possible for a limited time, as a courtesy for those who still cannot migrate yet, but these are strongly not recommended for ongoing production use as our strict adherence to semver backward compatibility guarantees limit many dependencies and we can only upgrade them so far without breaking compatibility. So there are likely known CVEs that cannot be resolved.

We recommend upgrading to Flux v2 which is actively maintained ASAP.

I am going to go ahead and close every issue at once today,
Thanks for participating in Helm Operator and Flux! 💚 💙
