### ISSUE TITLE
Trigger manual chart sync via API

### ISSUE THREAD

**Issue by varac** [fluxcd/helm-operator#467]
**Describe the feature**

I'd like to trigger a manual chart symc via API, similar to using curl for [Notifying the Helm Operator about Git changes](https://docs.fluxcd.io/projects/helm-operator/en/stable/helmrelease-guide/chart-sources/#notifying-the-helm-operator-about-git-changes).

**What would the new user story look like?**

0. A deployed helm release using helm-operator, with a chartsSyncInterval of 20m
1. The helm chart gets its values from a secret, i.e.:
    ```
      valuesFrom:
      - secretKeyRef:
          name: prometheus-settings
          key: values.yaml
    ```
2. The user changes value A in the secret.
3. Since there's no git change the helm-operator can react on, it's not possible to trigger an helm release upgrade manually, and the user needs to wait until the next chart sync
4. With the requested feature, the user could short-cut this and trigger a chart sync with i.e.

    curl -XPOST http://localhost:3030/api/v1/sync-chart

**Expected behavior**

After the curl cmd. above a chart sync will start, picking up the changes from the secret and uprading the release.

**Comment by varac** [comment]
Maybe there's this API endpoint already, but I didn't find any more documentation of the API.

**Comment by seaneagan** [comment]
#453 should accomplish the same goal (manually triggering upgrades), but in a more declarative and operator-driven way.

**Comment by kingdonb** [comment]
Sorry if your issue remains unresolved. The Helm Operator is in maintenance mode, we recommend everybody upgrades to Flux v2 and Helm Controller.

A new release of Helm Operator is out this week, 1.4.4.

We will continue to support Helm Operator in maintenance mode for an indefinite period of time, and eventually archive this repository.

Please be aware that Flux v2 has a vibrant and active developer community who are actively working through minor releases and delivering new features on the way to General Availability for Flux v2.

In the mean time, this repo will still be monitored, but support is basically limited to migration issues only. I will have to close many issues today without reading them all in detail because of time constraints. If your issue is very important, you are welcome to reopen it, but due to staleness of all issues at this point a new report is more likely to be in order. Please open another issue if you have unresolved problems that prevent your migration in the appropriate Flux v2 repo.

Helm Operator releases will continue as possible for a limited time, as a courtesy for those who still cannot migrate yet, but these are strongly not recommended for ongoing production use as our strict adherence to semver backward compatibility guarantees limit many dependencies and we can only upgrade them so far without breaking compatibility. So there are likely known CVEs that cannot be resolved.

We recommend upgrading to Flux v2 which is actively maintained ASAP.

I am going to go ahead and close every issue at once today,
Thanks for participating in Helm Operator and Flux! 💚 💙
