### ISSUE TITLE
Improve documentation for the S3 plugin

### ISSUE THREAD

**Issue by guidoffm** [fluxcd/helm-operator#474]
For the S3 plugin we need this environment variable:

...
    --set 'extraEnvs[0].name=AWS_DEFAULT_REGION' \
    --set 'extraEnvs[0].value=eu-central-1' \
...

**Comment by netflash** [comment]
I hit this bug yesterday when I tried to add the plugin. Came to almost the same concussion - in my case the variable is named `AWS_REGION`. I guess both works.

**Comment by hiddeco** [comment]
This is documented in the way that there is a note about most plugins expecting some way of configuration (https://docs.fluxcd.io/projects/helm-operator/en/stable/references/chart/#use-helm-downloader-plugins):

> Note: Most plugins assume credentials are available on the system they run on, make sure those are available at the expected paths using e.g. `extraVolumes` and `extraVolumeMounts`.

Given the example is about S3, I am happy to accept any PR that adds the above to the guide.

**Comment by kingdonb** [comment]
Sorry if your issue remains unresolved. The Helm Operator is in maintenance mode, we recommend everybody upgrades to Flux v2 and Helm Controller.

A new release of Helm Operator is out this week, 1.4.4.

We will continue to support Helm Operator in maintenance mode for an indefinite period of time, and eventually archive this repository.

Please be aware that Flux v2 has a vibrant and active developer community who are actively working through minor releases and delivering new features on the way to General Availability for Flux v2.

In the mean time, this repo will still be monitored, but support is basically limited to migration issues only. I will have to close many issues today without reading them all in detail because of time constraints. If your issue is very important, you are welcome to reopen it, but due to staleness of all issues at this point a new report is more likely to be in order. Please open another issue if you have unresolved problems that prevent your migration in the appropriate Flux v2 repo.

Helm Operator releases will continue as possible for a limited time, as a courtesy for those who still cannot migrate yet, but these are strongly not recommended for ongoing production use as our strict adherence to semver backward compatibility guarantees limit many dependencies and we can only upgrade them so far without breaking compatibility. So there are likely known CVEs that cannot be resolved.

We recommend upgrading to Flux v2 which is actively maintained ASAP.

I am going to go ahead and close every issue at once today,
Thanks for participating in Helm Operator and Flux! 💚 💙
