### ISSUE TITLE
Generated `releaseName` is Too Long

### ISSUE THREAD

**Issue by jeff-minard-ck** [fluxcd/helm-operator#477]
## Describe the bug

When you have long namespace and `HelmRelease` names, the generated `releaseName` can be too long and cause a deployment failure to the tune of:

```
failed to retrieve release 'super-long-combined-name-here-that-is-invalide-because-its-too-long': releaseContent: Release name is invalid: super-long-combined-name-here-that-is-invalide-because-its-too-long
```

## Details

The code which makes up this value, when not provided, seems to live here:

https://github.com/fluxcd/helm-operator/blob/master/pkg/apis/helm.fluxcd.io/v1/types_helmrelease.go#L47-L65

It would be great it the generated names would do a length check, and if too long, shorten the value up with a postfix that makes it unique. Personally, I've done something where I md5 the full string, take the first 6 characters of the md5, and post fix that on. For example:

```
super-long-combined-name-here-that-is-invalide-because-its-too-long
md5(super-long-combined-name-here-that-is-invalide-because-its-too-long)
 = cecf222bcf2def0d0a349a38c4a72ac2
```
to
```
super-long-combined-name-here-that-is-invalide-because-its-cecf22
```

Or something to that effect. No strong opinion on how uniqueness is achieved, just that the auto generated names don't cause failure.

## To Reproduce

Have a `HelmRelease` with long namespace/name values:
```yaml
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: this-helm-release-is-also-very-long-and-valid
  namespace: this-namespace-is-valid-but-also-long
```

This is double worse if the targetnamespace is different, as the string gets even longer :)

## Expected behavior

The helm operator shortens the auto-generated releaseName to something reproducible, unique, and within acceptable string lengths when auto-generating releaseNames's

**Comment by kingdonb** [comment]
Sorry if your issue remains unresolved. The Helm Operator is in maintenance mode, we recommend everybody upgrades to Flux v2 and Helm Controller.

A new release of Helm Operator is out this week, 1.4.4.

We will continue to support Helm Operator in maintenance mode for an indefinite period of time, and eventually archive this repository.

Please be aware that Flux v2 has a vibrant and active developer community who are actively working through minor releases and delivering new features on the way to General Availability for Flux v2.

In the mean time, this repo will still be monitored, but support is basically limited to migration issues only. I will have to close many issues today without reading them all in detail because of time constraints. If your issue is very important, you are welcome to reopen it, but due to staleness of all issues at this point a new report is more likely to be in order. Please open another issue if you have unresolved problems that prevent your migration in the appropriate Flux v2 repo.

Helm Operator releases will continue as possible for a limited time, as a courtesy for those who still cannot migrate yet, but these are strongly not recommended for ongoing production use as our strict adherence to semver backward compatibility guarantees limit many dependencies and we can only upgrade them so far without breaking compatibility. So there are likely known CVEs that cannot be resolved.

We recommend upgrading to Flux v2 which is actively maintained ASAP.

I am going to go ahead and close every issue at once today,
Thanks for participating in Helm Operator and Flux! 💚 💙
