### ISSUE TITLE
Helm Operator doesn't re-create a deleted deployment

### ISSUE THREAD

**Issue by Gui13** [fluxcd/helm-operator#497]
**Describe the bug**

Helm operator won't maintain the presence of a deployment even though the associated chart mandates its presence.

**To Reproduce**

- I install a Helm release that tells which chart to install
- The chart specifies that a deployment should be present
- All installs well, deployment is present and the associated pods are spawned
- I Issue `kubectl delete $deployment` in my shell
- The deployment is removed (and associated pods)
- The deployment is never re-created by helm operator.

**Expected behavior**

Helm operator should see that the deployment mandated by the chart has disappeared, and should have created it again

**Logs**

**Additional context**

- Helm Operator version: 1.1.0
- Kubernetes version: 1.15
- Git provider: azure devops
- Helm repository provider: Azure Container Registry

**Comment by hiddeco** [comment]
Cluster-state mutations are out-of-scope for the Helm Operator at the moment. As described in the feature list:

> Detection and recovery from **Helm storage mutations** (e.g. a manual Helm release that was made but conflicts with the declared configuration for the release)

From: https://docs.fluxcd.io/projects/helm-operator/en/stable/#features

**Comment by rayisbadat** [comment]
is this something on the roadmap for flux/helm-operator v2? To reconcile the helm-chart vs current state of cluster ?

**Comment by InsOpDe** [comment]
Is there a way to force install everything (i.e. every removed deployment)?

**Comment by kingdonb** [comment]
Sorry if your issue remains unresolved. The Helm Operator is in maintenance mode, we recommend everybody upgrades to Flux v2 and Helm Controller.

A new release of Helm Operator is out this week, 1.4.4.

We will continue to support Helm Operator in maintenance mode for an indefinite period of time, and eventually archive this repository.

Please be aware that Flux v2 has a vibrant and active developer community who are actively working through minor releases and delivering new features on the way to General Availability for Flux v2.

In the mean time, this repo will still be monitored, but support is basically limited to migration issues only. I will have to close many issues today without reading them all in detail because of time constraints. If your issue is very important, you are welcome to reopen it, but due to staleness of all issues at this point a new report is more likely to be in order. Please open another issue if you have unresolved problems that prevent your migration in the appropriate Flux v2 repo.

Helm Operator releases will continue as possible for a limited time, as a courtesy for those who still cannot migrate yet, but these are strongly not recommended for ongoing production use as our strict adherence to semver backward compatibility guarantees limit many dependencies and we can only upgrade them so far without breaking compatibility. So there are likely known CVEs that cannot be resolved.

We recommend upgrading to Flux v2 which is actively maintained ASAP.

I am going to go ahead and close every issue at once today,
Thanks for participating in Helm Operator and Flux! 💚 💙
