### ISSUE TITLE
Operator doesn't recover from failure to get repository index.yaml from artifactory

### ISSUE THREAD

**Issue by saada** [fluxcd/helm-operator#504]
**Describe the bug**

When the operator hits this error log:

```
{"caller":"repository.go:112","component":"helm","error":"Get \"https://artifactory.mydomain.com/helm-releases/index.yaml\": dial tcp: lookup artifactory.mydomain.com on 172.20.0.10
```

It never recovers and fails to fetch any charts in that repository.

```
unavailable: chart "<REDACTED-CHARTNAME>" version "2.0.1" not found in https://artifactory.mydomain.com/helm-releases/ repository
```

The only way to workaround this is to restart the operator.

**To Reproduce**

1. Turn off artifactory
2. Spin up helm operator and deploy any release from artifactory (you should see error)
3. Turn on artifactory (you should see it never recovers from the failure)

**Expected behavior**

When artifactory comes back online, the index.yaml should be pulled and everything should start working automatically.

**Logs**

Logs were shown in bug description above.

**Additional context**

- Helm Operator version: master-f8ec9597
- Kubernetes version: 1.15
- Git provider: N/A
- Helm repository provider: Artifactory

**Comment by kingdonb** [comment]
Sorry if your issue remains unresolved. The Helm Operator is in maintenance mode, we recommend everybody upgrades to Flux v2 and Helm Controller.

A new release of Helm Operator is out this week, 1.4.4.

We will continue to support Helm Operator in maintenance mode for an indefinite period of time, and eventually archive this repository.

Please be aware that Flux v2 has a vibrant and active developer community who are actively working through minor releases and delivering new features on the way to General Availability for Flux v2.

In the mean time, this repo will still be monitored, but support is basically limited to migration issues only. I will have to close many issues today without reading them all in detail because of time constraints. If your issue is very important, you are welcome to reopen it, but due to staleness of all issues at this point a new report is more likely to be in order. Please open another issue if you have unresolved problems that prevent your migration in the appropriate Flux v2 repo.

Helm Operator releases will continue as possible for a limited time, as a courtesy for those who still cannot migrate yet, but these are strongly not recommended for ongoing production use as our strict adherence to semver backward compatibility guarantees limit many dependencies and we can only upgrade them so far without breaking compatibility. So there are likely known CVEs that cannot be resolved.

We recommend upgrading to Flux v2 which is actively maintained ASAP.

I am going to go ahead and close every issue at once today,
Thanks for participating in Helm Operator and Flux! 💚 💙
