### ISSUE TITLE
Allow helm-operator to pick up release changes due to cluster capabilities' changes

### ISSUE THREAD

**Issue by tommasopozzetti** [fluxcd/helm-operator#508]
The problem I'm trying to solve derives from trying to manage several K8s clusters entirely with helm-operator. We have several charts that exploit several CRDs and utilize the `.Capabilities.APIVersions.Has` Helm feature to conditionally create those manifests only if the CRDs are installed in the cluster. A simple example is the case of a Prometheus PodMonitor resource. We don't want an application to fail installation if Prometheus has never been installed on that cluster but we want it to provide the PodMonitor as soon as Prometheus gets installed.
Running a helm-diff (or a dry-run install and comparing manifests) should template the resources based on cluster capabilities, so, for example, upon adding the PodMonitor CRD, it should show that a new manifest is available and therefore the helm release requires an upgrade.
However, because of the way helm-operator looks at diffs ([here](https://github.com/fluxcd/helm-operator/blob/v1.2.0/pkg/helm/utils.go#L7)), it only requires a helm upgrade to be performed if something changes in terms of values or chart, which is not the case for a cluster capability change.
By searching through issues and documentation it looks like the choice of not comparing manifests is more of a design decision ([here](https://github.com/fluxcd/helm-operator/pull/444#issuecomment-639116910)).

I'm wondering whether there is any plan to add a feature to allow helm-operator to pick up on those subtle changes and upgrade releases, maybe even just as a configurable option per HelmRelease (so as to allow it to be disabled for charts that use timestamps or any form of dynamically templated manifest that would bring constant useless upgrades).
Alternatively, is there a better way to achieve this result?

The final behavior I'm looking for would be for example being able to take a new empty K8s cluster and just let helm-operator install everything from a collection of HelmRelease resources. Because the install order is not specified, some apps might get installed before some CRDs become available and therefore might be missing those manifests. Ideally I wouldn't worry about this as helm-operator will pick up the changes as soon as the CRDs become available and upgrade the releases to include those manifests.

**Comment by kingdonb** [comment]
Sorry if your issue remains unresolved. The Helm Operator is in maintenance mode, we recommend everybody upgrades to Flux v2 and Helm Controller.

A new release of Helm Operator is out this week, 1.4.4.

We will continue to support Helm Operator in maintenance mode for an indefinite period of time, and eventually archive this repository.

Please be aware that Flux v2 has a vibrant and active developer community who are actively working through minor releases and delivering new features on the way to General Availability for Flux v2.

In the mean time, this repo will still be monitored, but support is basically limited to migration issues only. I will have to close many issues today without reading them all in detail because of time constraints. If your issue is very important, you are welcome to reopen it, but due to staleness of all issues at this point a new report is more likely to be in order. Please open another issue if you have unresolved problems that prevent your migration in the appropriate Flux v2 repo.

Helm Operator releases will continue as possible for a limited time, as a courtesy for those who still cannot migrate yet, but these are strongly not recommended for ongoing production use as our strict adherence to semver backward compatibility guarantees limit many dependencies and we can only upgrade them so far without breaking compatibility. So there are likely known CVEs that cannot be resolved.

We recommend upgrading to Flux v2 which is actively maintained ASAP.

I am going to go ahead and close every issue at once today,
Thanks for participating in Helm Operator and Flux! 💚 💙
