### ISSUE TITLE
namespace value not rendered properly

### ISSUE THREAD

**Issue by mbrancato** [fluxcd/helm-operator#516]
**Describe the bug**
**Updated:**
When deploying the helm-operator, the namespaced resources are not rendered with `namespace` metadata when using `helm template`. This may be a bug in Helm.

This works with:
```
helm upgrade -i helm-operator fluxcd/helm-operator --namespace flux --set helm.versions=v3 --set image.tag="1.2.0"
```

But it does not work with:
```
helm template helm-operator fluxcd/helm-operator --namespace flux --set helm.versions=v3 --set image.tag="1.2.0" | kubectl apply -f -
```

In the latter, the `helm-operator` Deployment is created in the `default` namespace but the ClusterRoleBinding is created in the `flux` Namespace.

**Expected behavior**
There should be a Namespace assigned to the namespaced resources.

**Logs**
```
E0815 15:09:59.659266       6 reflector.go:153] github.com/fluxcd/helm-operator/pkg/client/informers/externalversions/factory.go:117: Failed to list *v1.HelmRelease: helmreleases.helm.fluxcd.io is forbidden: User "system:serviceaccount:default:helm-operator" cannot list resource "helmreleases" in API group "helm.fluxcd.io" at the cluster scope
E0815 15:10:00.663609       6 reflector.go:153] github.com/fluxcd/helm-operator/pkg/client/informers/externalversions/factory.go:117: Failed to list *v1.HelmRelease: helmreleases.helm.fluxcd.io is forbidden: User "system:serviceaccount:default:helm-operator" cannot list resource "helmreleases" in API group "helm.fluxcd.io" at the cluster scope
E0815 15:10:01.666876       6 reflector.go:153] github.com/fluxcd/helm-operator/pkg/client/informers/externalversions/factory.go:117: Failed to list *v1.HelmRelease: helmreleases.helm.fluxcd.io is forbidden: User "system:serviceaccount:default:helm-operator" cannot list resource "helmreleases" in API group "helm.fluxcd.io" at the cluster scope
```

**Additional context**
Add any other context about the problem here, e.g 
- Helm Operator version: 1.2.0
- Targeted Helm version: 3.3.0
- Kubernetes version: 1.18.1
- Git provider: Github
- Container registry provider: docker.io

**Comment by mbrancato** [comment]
I probably incorrectly assumed this namespace value was to blame. I fixed this by adding the `.metadata.namespace` field to the namespaced resources which currently lack the key `.metadata.namespace`. Apparently helm seems to automatically add this when using `helm upgrade -i`.

**Comment by mikesir87** [comment]
Same thing occurred to me (error logs and all) when I downloaded the YAML files and applied them using kustomize (made my own kustomization.yaml file). When I added the `namespace` key to the kustomization.yaml file, everything deployed just fine.

**Comment by kingdonb** [comment]
Sorry if your issue remains unresolved. The Helm Operator is in maintenance mode, we recommend everybody upgrades to Flux v2 and Helm Controller.

A new release of Helm Operator is out this week, 1.4.4.

We will continue to support Helm Operator in maintenance mode for an indefinite period of time, and eventually archive this repository.

Please be aware that Flux v2 has a vibrant and active developer community who are actively working through minor releases and delivering new features on the way to General Availability for Flux v2.

In the mean time, this repo will still be monitored, but support is basically limited to migration issues only. I will have to close many issues today without reading them all in detail because of time constraints. If your issue is very important, you are welcome to reopen it, but due to staleness of all issues at this point a new report is more likely to be in order. Please open another issue if you have unresolved problems that prevent your migration in the appropriate Flux v2 repo.

Helm Operator releases will continue as possible for a limited time, as a courtesy for those who still cannot migrate yet, but these are strongly not recommended for ongoing production use as our strict adherence to semver backward compatibility guarantees limit many dependencies and we can only upgrade them so far without breaking compatibility. So there are likely known CVEs that cannot be resolved.

We recommend upgrading to Flux v2 which is actively maintained ASAP.

I am going to go ahead and close every issue at once today,
Thanks for participating in Helm Operator and Flux! 💚 💙
