### ISSUE TITLE
Question - Helm Operator metrics regarding Helm Releases

### ISSUE THREAD

**Issue by Galileo1** [fluxcd/helm-operator#518]
We would like to have more clarity on the [documentation](https://docs.fluxcd.io/projects/helm-operator/en/stable/references/monitoring/) for monitoring Helm Operator for Helm Releases. 

We cannot find how we can get the following info. There could be gap in understanding as well. But if you can shed some light on this. It will be helpful.

- the current active Helm Release detailed info. `flux_helm_operator_release_count` only shows the count and not the details. And `flux_helm_operator_release_condition_info` only shows **Released** or **Chart Fetched** conditions. 

- mean time to install a Helm Release(when Helm Release transitions phase from "Installing" to "succeeded" and status is "deployed").

- mean time to upgrade a Helm Release(when we patch a release using Kubernetes api. It captures the generations but doesn't doesn't show any data regarding each generation)

Also when we query data in Prometheus regarding the `flux_helm_operator_release_action` or `flux_helm_operator_release_phase` or `flux_helm_operator_release_duration`. It does show data about the active releases rather all the release. There must be a way to query active Helm Releases.

**Comment by kingdonb** [comment]
Sorry if your issue remains unresolved. The Helm Operator is in maintenance mode, we recommend everybody upgrades to Flux v2 and Helm Controller.

A new release of Helm Operator is out this week, 1.4.4.

We will continue to support Helm Operator in maintenance mode for an indefinite period of time, and eventually archive this repository.

Please be aware that Flux v2 has a vibrant and active developer community who are actively working through minor releases and delivering new features on the way to General Availability for Flux v2.

In the mean time, this repo will still be monitored, but support is basically limited to migration issues only. I will have to close many issues today without reading them all in detail because of time constraints. If your issue is very important, you are welcome to reopen it, but due to staleness of all issues at this point a new report is more likely to be in order. Please open another issue if you have unresolved problems that prevent your migration in the appropriate Flux v2 repo.

Helm Operator releases will continue as possible for a limited time, as a courtesy for those who still cannot migrate yet, but these are strongly not recommended for ongoing production use as our strict adherence to semver backward compatibility guarantees limit many dependencies and we can only upgrade them so far without breaking compatibility. So there are likely known CVEs that cannot be resolved.

We recommend upgrading to Flux v2 which is actively maintained ASAP.

I am going to go ahead and close every issue at once today,
Thanks for participating in Helm Operator and Flux! 💚 💙
