### ISSUE TITLE
Helm-operator CrashLoopBackOff when helm.fluxcd.io/migrate annotation is set and no Tiller in the cluster

### ISSUE THREAD

**Issue by ttarczynski** [fluxcd/helm-operator#528]
**Describe the bug**

After migration from helm v2 to v3 I've seen `helm-operator` going into `CrashLoopBackOff` state. The last error msg seen in logs is: `Found 0 tiller pods`.

It happens only if:
* There is no Tiller pod in the cluster
* There is a helm release with an annotation: `helm.fluxcd.io/migrate`
  * and it's regardless of the annotation value: both `"false"` and `"true"` cause the `helm-operator` crash

**To Reproduce**

Here are the minimal steps to reproduce this behaviour:
1. Have a k8s cluster without Tiller
2. Install Helm Operator with `helm.versions=v3`:
    ```
    # kubectl apply -f https://raw.githubusercontent.com/fluxcd/helm-operator/1.2.0/deploy/crds.yaml
    # helm upgrade -i helm-operator fluxcd/helm-operator --namespace flux --set helm.versions=v3
    ```
3. Install the following HelmRelease:
    ```
    apiVersion: helm.fluxcd.io/v1
    kind: HelmRelease
    metadata:
      name: podinfo
      namespace: default
      annotations:
        helm.fluxcd.io/migrate: "true"
    spec:
      chart:
        repository: https://stefanprodan.github.io/podinfo
        name: podinfo
        version: 4.0.6
    ```
4. The HelmRelease status observed:
    ```
    # kubectl describe helmrelease -n default podinfo
    Name:         podinfo
    Namespace:    default
    Labels:       <none>
    Annotations:  helm.fluxcd.io/migrate: true
    API Version:  helm.fluxcd.io/v1
    Kind:         HelmRelease
    Metadata:
      Creation Timestamp:  2020-09-08T18:16:24Z
      Generation:          1
      Managed Fields:
        [redacted]
      Resource Version:  4374484
      Self Link:         /apis/helm.fluxcd.io/v1/namespaces/default/helmreleases/podinfo
      UID:               57d912b7-f327-4552-8dfd-39cf497a23d4
    Spec:
      Chart:
        Name:        podinfo
        Repository:  https://stefanprodan.github.io/podinfo
        Version:     4.0.6
    Status:
      Conditions:
        Last Transition Time:  2020-09-08T18:16:24Z
        Last Update Time:      2020-09-08T18:17:08Z
        Message:               Chart fetch was successful for Helm release 'default-podinfo' in 'default'.
        Reason:                ChartFetched
        Status:                True
        Type:                  ChartFetched
      Phase:                   ChartFetched
    Events:                    <none>
    ```
5. See the `helm-operator` crash:
    ```
    # kubectl get pod -n flux  -l app=helm-operator
    NAME                             READY   STATUS             RESTARTS   AGE
    helm-operator-7c78f5f866-8w2fl   0/1     CrashLoopBackOff   5          66m
    ```

**Expected behavior**

The release should work regardless of the `helm.fluxcd.io/migrate` annotation value. When I'm done with the migration to helm v3, I configure the `helm-operator` to: `helm.versions=v3` and I expect it to ignore the `helm.fluxcd.io/migrate` annotation completly.

**Logs**

Whole logs from the crashed helm-operator POD:
```
ts=2020-09-08T18:17:55.35527069Z caller=operator.go:86 component=operator info="setting up event handlers"
ts=2020-09-08T18:17:55.355695146Z caller=operator.go:107 component=operator info="event handlers set up"
ts=2020-09-08T18:17:55.355906885Z caller=main.go:300 component=helm-operator info="waiting for informer caches to sync"
ts=2020-09-08T18:17:55.45623428Z caller=main.go:305 component=helm-operator info="informer caches synced"
ts=2020-09-08T18:17:55.471431426Z caller=operator.go:119 component=operator info="starting operator"
ts=2020-09-08T18:17:55.471769619Z caller=operator.go:121 component=operator info="starting workers"
ts=2020-09-08T18:17:55.472283696Z caller=release.go:79 component=release release=default-podinfo targetNamespace=default resource=default:helmrelease/podinfo helmVersion=v3 info="starting sync run"
ts=2020-09-08T18:17:55.473176791Z caller=git.go:104 component=gitchartsync info="starting sync of git chart sources"
ts=2020-09-08T18:17:55.473570273Z caller=server.go:42 component=daemonhttp info="starting HTTP server on :3030"
ts=2020-09-08T18:17:55.901399345Z caller=logwriter.go:28 info="2020/09/08 18:17:55 Found 0 tiller pods"
```

**Additional context**

- Helm Operator version: 1.2.0
- Kubernetes version: v1.18.8
- Git provider: not used
- Helm repository provider: `repository: https://stefanprodan.github.io/podinfo`
- Helm version: v3.3.1

Also checked if `helmVersion: v3` in the HelmRelease spec makes any difference here and it doesn't.

**Comment by kingdonb** [comment]
Sorry if your issue remains unresolved. The Helm Operator is in maintenance mode, we recommend everybody upgrades to Flux v2 and Helm Controller.

A new release of Helm Operator is out this week, 1.4.4.

We will continue to support Helm Operator in maintenance mode for an indefinite period of time, and eventually archive this repository.

Please be aware that Flux v2 has a vibrant and active developer community who are actively working through minor releases and delivering new features on the way to General Availability for Flux v2.

In the mean time, this repo will still be monitored, but support is basically limited to migration issues only. I will have to close many issues today without reading them all in detail because of time constraints. If your issue is very important, you are welcome to reopen it, but due to staleness of all issues at this point a new report is more likely to be in order. Please open another issue if you have unresolved problems that prevent your migration in the appropriate Flux v2 repo.

Helm Operator releases will continue as possible for a limited time, as a courtesy for those who still cannot migrate yet, but these are strongly not recommended for ongoing production use as our strict adherence to semver backward compatibility guarantees limit many dependencies and we can only upgrade them so far without breaking compatibility. So there are likely known CVEs that cannot be resolved.

We recommend upgrading to Flux v2 which is actively maintained ASAP.

I am going to go ahead and close every issue at once today,
Thanks for participating in Helm Operator and Flux! 💚 💙
