### ISSUE TITLE
High network traffic

### ISSUE THREAD

**Issue by laszlocph** [fluxcd/helm-operator#538]
The Helm Operator has a constant downstream traffic of ~200kB/s.

I can see why the Helm Operator syncs periodically with chart repos to get the latest chart info, but this traffic seems excessive.
Is it normal?

**To Reproduce**

Install the Helm Operator with yamls: https://docs.fluxcd.io/projects/helm-operator/en/stable/get-started/using-yamls/
Add a few HelmReleases with different repos like https://kubernetes-charts.storage.googleapis.com and https://grafana.github.io/helm-charts

**Expected behavior**

No excessive network traffic

**Logs**
No related log lines

**Additional context**

- Helm Operator version: helm-operator:1.1.0
- Kubernetes version: 1.17.11
- Git provider: Github
- Helm repository provider: stable, grafana, prometheus-community

**Comment by laszlocph** [comment]
![Screenshot from 2020-09-23 11-15-11](https://user-images.githubusercontent.com/4289031/93992823-4dc28b00-fd8e-11ea-9179-9481f2d4d87b.png)

**Comment by rafaelgaspar** [comment]
Since most of this traffic is received, I would assume those are coming from the Kubernetes API that it watches for some resources.

**Comment by kingdonb** [comment]
Sorry if your issue remains unresolved. The Helm Operator is in maintenance mode, we recommend everybody upgrades to Flux v2 and Helm Controller.

A new release of Helm Operator is out this week, 1.4.4.

We will continue to support Helm Operator in maintenance mode for an indefinite period of time, and eventually archive this repository.

Please be aware that Flux v2 has a vibrant and active developer community who are actively working through minor releases and delivering new features on the way to General Availability for Flux v2.

In the mean time, this repo will still be monitored, but support is basically limited to migration issues only. I will have to close many issues today without reading them all in detail because of time constraints. If your issue is very important, you are welcome to reopen it, but due to staleness of all issues at this point a new report is more likely to be in order. Please open another issue if you have unresolved problems that prevent your migration in the appropriate Flux v2 repo.

Helm Operator releases will continue as possible for a limited time, as a courtesy for those who still cannot migrate yet, but these are strongly not recommended for ongoing production use as our strict adherence to semver backward compatibility guarantees limit many dependencies and we can only upgrade them so far without breaking compatibility. So there are likely known CVEs that cannot be resolved.

We recommend upgrading to Flux v2 which is actively maintained ASAP.

I am going to go ahead and close every issue at once today,
Thanks for participating in Helm Operator and Flux! 💚 💙
