### ISSUE TITLE
drift between the helm chart deployment vs definition

### ISSUE THREAD

**Issue by amit-handda** [fluxcd/helm-operator#543]
**Describe the bug**

open-policy-agent chart is stored in the git repo. It is deployed as a helmrelease. Even though, Its OPA policies have been updated in git repo, the deployment shows OPA policies belonging to previous commit. The OPA policies were updated in git repo more than a month back.
  
**To Reproduce**

Steps to reproduce the behaviour:
1. Provide the Helm Operator install instructions
we deployed helm-operator as a helm chart with following values
```
helm-operator:
  image:
    repository: docker.io/fluxcd/helm-operator
    tag: 1.1.0

  helm:
    versions: v3

  git:
    ssh:
      secretName: flux-git-deploy
```

2. Provide a HelmRelease example
we have copied helm stable chart https://github.com/helm/charts/tree/master/stable/opa. thats it.

values.yaml snippet of open-policy-agent values 
```
# Docker image and tag to deploy.
image: openpolicyagent/opa
imageTag: 0.22.0
imagePullPolicy: IfNotPresent
```

3. Post the HelmRelease status, you can get this by running `kubectl describe helmrelease <name>`

```
Name:         open-policy-agent
Namespace:    infra-system
Labels:       fluxcd.io/sync-gc-mark=sha256.6NZ07ibiQ-fDS0DjHsCUuRmIGcYQ8DZdLOVglHLkFjQ
Annotations:  fluxcd.io/sync-checksum: 1dd1b1d1d90e8482dd0bef995bbb24e146c971d0
API Version:  helm.fluxcd.io/v1
Kind:         HelmRelease
Metadata:
  Creation Timestamp:  2020-04-24T23:53:25Z
  Generation:          1
  Resource Version:    153874973
  Self Link:           /apis/helm.fluxcd.io/v1/namespaces/infra-system/helmreleases/open-policy-agent
  UID:                 48adb541-028c-4450-bfa4-935f38750868
Spec:
  Chart:
    Git:         git@github.com:doordash/cluster-config
    Path:        charts/open-policy-agent
    Ref:         master
  Release Name:  open-policy-agent
  Values:
    Policy Set:  prod
    Resources:
      Limits:
        Cpu:     200m
        Memory:  200Mi
      Requests:
        Cpu:     100m
        Memory:  200Mi
Status:
  Conditions:
    Last Transition Time:  2020-08-25T00:56:16Z
    Last Update Time:      2020-08-25T00:56:16Z
    Message:               Chart fetch failed for Helm release 'open-policy-agent' in 'infra-system'.
    Reason:                ChartFetchFailed
    Status:                False
    Type:                  ChartFetched
    Last Transition Time:  2020-08-25T00:59:27Z
    Last Update Time:      2020-10-02T17:54:15Z
    Message:               Release was successful for Helm release 'open-policy-agent' in 'infra-system'.
    Reason:                Succeeded
    Status:                True
    Type:                  Released
  Observed Generation:     1
  Phase:                   Succeeded
  Release Name:            open-policy-agent
  Release Status:          deployed
  Revision:                72fdbceb58115342b2b9ca1eea9b5b167c34ca21
Events:
  Type    Reason         Age                      From           Message
  ----    ------         ----                     ----           -------
  Normal  ReleaseSynced  3m24s (x12754 over 38d)  helm-operator  managed release 'open-policy-agent' in namespace 'infra-system' synchronized
```

**Expected behavior**

The `Revision` in the above helm-release describe should be the latest one. It is showing obsolete one.
`git log` for the `chart` is as follows

```
commit e3391e60b8466e35c0962a61890b5bdc9e51e651
Author: user3@users.noreply.github.com>
Date:   Tue Sep 1 12:49:54 2020 -0700

log msg

commit 156696b8aee92f0142ff385c9c6e5f5aff98ff29
Author: user2@users.noreply.github.com>
Date:   Mon Aug 3 13:49:25 2020 -0700

log msg

commit 72fdbceb58115342b2b9ca1eea9b5b167c34ca21
Author: user1@users.noreply.github.com>
Date:   Wed Jul 29 11:28:13 2020 -0700

    update OPA - set imageTag in the chart (#777)
```

**Logs**

If applicable, please provide logs. In a standard stand-alone installation, you'd get this by running `kubectl logs deploy/flux-helm-operator -n fluxcd`.

helm-operator logs are mostly a loop of following:

```❯ k logs -n flux helm-operator-5b78c7dfd6-cltbs | grep open-policy```

```ts=2020-10-02T18:11:45.464350362Z caller=release.go:75 component=release release=open-policy-agent targetNamespace=infra-system resource=infra-system:helmrelease/open-policy-agent helmVersion=v3 info="starting sync run"
ts=2020-10-02T18:11:51.863658097Z caller=release.go:251 component=release release=open-policy-agent targetNamespace=infra-system resource=infra-system:helmrelease/open-policy-agent helmVersion=v3 info="running dry-run upgrade to compare with release version '4'" action=dry-run-compare
ts=2020-10-02T18:11:51.866127533Z caller=helm.go:69 component=helm version=v3 info="preparing upgrade for open-policy-agent" targetNamespace=infra-system release=open-policy-agent
ts=2020-10-02T18:11:51.874294411Z caller=helm.go:69 component=helm version=v3 info="resetting values to the chart's original version" targetNamespace=infra-system release=open-policy-agent
ts=2020-10-02T18:12:11.366219551Z caller=helm.go:69 component=helm version=v3 info="performing update for open-policy-agent" targetNamespace=infra-system release=open-policy-agent
ts=2020-10-02T18:12:11.666020656Z caller=helm.go:69 component=helm version=v3 info="dry run for open-policy-agent" targetNamespace=infra-system release=open-policy-agent
ts=2020-10-02T18:12:13.276978349Z caller=release.go:273 component=release release=open-policy-agent targetNamespace=infra-system resource=infra-system:helmrelease/open-policy-agent helmVersion=v3 info="no changes" phase=dry-run-compare
```

**Additional context**

- Helm Operator version: 1.1.0
- Kubernetes version: 1.17.9
- Git provider: github
- Helm repository provider: github

**Comment by kingdonb** [comment]
After reading this and hearing a similar report from someone actively experiencing this issue (in #flux slack channel), I have an educated guess on what might be the problem

> open-policy-agent chart is stored in the git repo. It is deployed as a helmrelease.

> Even though, Its OPA policies have been updated in git repo, the deployment shows OPA policies belonging to previous commit. The OPA policies were updated in git repo more than a month back.

When you updated the OPA policies in the helm chart, in the git repo, did you also increment the chart `Version`?

I've been supporting users of the Helm Controller (modern replacement of Helm Operator in Flux v2) and this is a common issue, if you did not increment `chart`.`Version` then a change in the chart templates is not expected, and will not be reconciled. In the modern situation, it is explainable through the CRDs of HelmChart and the sources API.

I suspect the same issue affects current Helm Operator versions. This only impacts users of git+helm combination, it is not a problem for HelmRepository users because the operational characteristics of a Helm Repository don't permit this misunderstanding of how Helm is meant to work.

The chart templates and default values.yaml are immutable with a given chart version.

If you did not update the chart version and you updated the chart template, then you will not get an update out of Helm.

Apologies if this issue has gone stale and you are no longer struggling with it. Please let me know if this helps, or if more assistance is needed. If not, we can close this issue.

**Comment by kingdonb** [comment]
I'm going to go ahead and close, based on discussion with the active reporter confirming my suspicions about how this problem is encountered, and some inspection of the problem characteristics, we gauge the likelihood is high that this is the same issue reported here.

It is not expected for Helm chart templates or values (defaults) to be updated within the same Chart Version. Helm Operator 1.2.0 works more like Helm Controller does, (and if this analysis holds water, then it will likely not be changed back.)

Sorry if this is not the answer that you were hoping for! Thanks for using Flux.

**Comment by ktaborski** [comment]
It would be good to document this in section:
https://docs.fluxcd.io/projects/helm-operator/en/stable/helmrelease-guide/reconciliation-and-upgrades/#what-triggers-an-upgrade
