### ISSUE TITLE
Sometimes two upgrades will occur instead of one

### ISSUE THREAD

**Issue by Simon3** [fluxcd/helm-operator#559]
**Describe the bug**
Sometimes, if I upgrade both the chart version and the values of my release, helm-operator will upgrade my release twice within a small time interval. It happens when helm-operator loop iteration (the one that enqueues releases and then upgrades them) occurs right after my push, i.e. before flux loop iteration (the one that updates helmrelease.helm.fluxcd.io resources). 
In consequence, there is first one upgrades that uses the new values but the old chart version, and then a second upgrade that uses the new chart version with the new values. That first upgrade with the old version of the chart can be very problematic in some cases. 

**To Reproduce**
Just upgrade both chart version and values right before an helm-operator iteration. 

**Expected behavior**
Only one upgrade should occur, with all modifications linked to the git push, i.e. new chart version AND new values.

**Additional context**
- Helm Operator version: see below
- Kubernetes version: 1.15
- Git provider: Bitbucket Server
- Helm repository provider: charts are stored in Bitbucket and referenced via "git", "path" and "ref" (in this case, it is the ref that is changing)
```
NAME         	NAMESPACE	REVISION	UPDATED                              	STATUS  	CHART              	APP VERSION
flux         	fluxcd   	5       	2020-04-15 13:42:28.969198 +0200 CEST	deployed	flux-1.2.0         	1.18.0     
helm-operator	fluxcd   	2       	2020-02-24 12:36:20.422283 +0100 CET 	deployed	helm-operator-0.7.0	1.0.0-rc9 
```

**Comment by kingdonb** [comment]
Sorry if your issue remains unresolved. The Helm Operator is in maintenance mode, we recommend everybody upgrades to Flux v2 and Helm Controller.

A new release of Helm Operator is out this week, 1.4.4.

We will continue to support Helm Operator in maintenance mode for an indefinite period of time, and eventually archive this repository.

Please be aware that Flux v2 has a vibrant and active developer community who are actively working through minor releases and delivering new features on the way to General Availability for Flux v2.

In the mean time, this repo will still be monitored, but support is basically limited to migration issues only. I will have to close many issues today without reading them all in detail because of time constraints. If your issue is very important, you are welcome to reopen it, but due to staleness of all issues at this point a new report is more likely to be in order. Please open another issue if you have unresolved problems that prevent your migration in the appropriate Flux v2 repo.

Helm Operator releases will continue as possible for a limited time, as a courtesy for those who still cannot migrate yet, but these are strongly not recommended for ongoing production use as our strict adherence to semver backward compatibility guarantees limit many dependencies and we can only upgrade them so far without breaking compatibility. So there are likely known CVEs that cannot be resolved.

We recommend upgrading to Flux v2 which is actively maintained ASAP.

I am going to go ahead and close every issue at once today,
Thanks for participating in Helm Operator and Flux! 💚 💙
