### ISSUE TITLE
Does helm-operator deploy chart from helm repo to another cluster?

### ISSUE THREAD

**Issue by ruchikaguptaa** [fluxcd/helm-operator#560]
**Describe the bug**
Helm-operator is not deploying helm chart out-of-cluster.

According to documentation we can provide [kubeconfig path](https://github.com/fluxcd/helm-operator/blob/90f49460e252bb60b3c8fe5593854c2c716c2236/cmd/helm-operator/main.go#L103) of another cluster where the target helm chart will get deployed.

But according to values.yaml I need to provide the [complete kubeconfig](https://github.com/fluxcd/helm-operator/blob/90f49460e252bb60b3c8fe5593854c2c716c2236/chart/helm-operator/values.yaml#L163-L177) 

So I override .kube.config in helm operator values.yaml chart like following. But the helm chart from the repo doesn't get deployed to the overlay cluster.

```
kube:
  # Override for kubectl default config
  config: |
    apiVersion: v1
    clusters:
    - cluster:
        certificate-authority-data: ..
        server: https://overlay-dns-d058a4e7.hcp.westeurope.azmk8s.io:443
      name: overlay
    contexts:
    - context:
        cluster: overlay
        user: clusterUser_rucguptDev_overlay
      name: overlay
    current-context: overlay
    kind: Config
    preferences: {}
    users:
    - name: clusterUser_rucguptDev_overlay
      user:
        client-certificate-data: ...
        client-key-data: ...
        token: ...
```

The ConfigMap with overlay cluster kubeconfig is created and I see the kubeconfig in "data" field.

```
MININT-DVQPRS9:github ruchikagupta$ kubectl get cm helm-operator-kube-config -n flux -o yaml
apiVersion: v1
data:
  config: |
    apiVersion: v1
    clusters:
    - cluster:
        certificate-authority-data: ...
        server: https://overlay-dns-d058a4e7.hcp.westeurope.azmk8s.io:443
      name: overlay
    contexts:
    - context:
        cluster: overlay
        user: clusterUser_rucguptDev_overlay
      name: overlay
    current-context: overlay
    kind: Config
    preferences: {}
    users:
    - name: clusterUser_rucguptDev_overlay
      user:
        client-certificate-data: ...
        client-key-data: ...
        token: ...
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: helm-operator
    meta.helm.sh/release-namespace: flux
  creationTimestamp: "2020-10-31T02:38:21Z"
  labels:
    app.kubernetes.io/managed-by: Helm
  name: helm-operator-kube-config
  namespace: flux
  resourceVersion: "77509"
  selfLink: /api/v1/namespaces/flux/configmaps/helm-operator-kube-config
  uid: 6a6320e9-07f6-4e26-bcfa-4e812be0b0c0
```

There are no error logs in the helm-operator pod either.

I came across this other [issue](https://github.com/fluxcd/helm-operator/issues/501) but that seems to be resolved. Is there some other issue? Or am I missing something?

**Comment by stefanprodan** [comment]
You can deploy to another cluster with Flux v2:
- [HelmRelease remote clusters docs](https://toolkit.fluxcd.io/components/helm/helmreleases/#remote-clusters-cluster-api)
- [Migrate to Helm Controller guide](https://toolkit.fluxcd.io/guides/helm-operator-migration/)

**Comment by kingdonb** [comment]
Sorry if your issue remains unresolved. The Helm Operator is in maintenance mode, we recommend everybody upgrades to Flux v2 and Helm Controller.

A new release of Helm Operator is out this week, 1.4.4.

We will continue to support Helm Operator in maintenance mode for an indefinite period of time, and eventually archive this repository.

Please be aware that Flux v2 has a vibrant and active developer community who are actively working through minor releases and delivering new features on the way to General Availability for Flux v2.

In the mean time, this repo will still be monitored, but support is basically limited to migration issues only. I will have to close many issues today without reading them all in detail because of time constraints. If your issue is very important, you are welcome to reopen it, but due to staleness of all issues at this point a new report is more likely to be in order. Please open another issue if you have unresolved problems that prevent your migration in the appropriate Flux v2 repo.

Helm Operator releases will continue as possible for a limited time, as a courtesy for those who still cannot migrate yet, but these are strongly not recommended for ongoing production use as our strict adherence to semver backward compatibility guarantees limit many dependencies and we can only upgrade them so far without breaking compatibility. So there are likely known CVEs that cannot be resolved.

We recommend upgrading to Flux v2 which is actively maintained ASAP.

I am going to go ahead and close every issue at once today,
Thanks for participating in Helm Operator and Flux! 💚 💙
