### ISSUE TITLE
Slow queue processing / syncs

### ISSUE THREAD

**Issue by danepowell** [fluxcd/helm-operator#566]
We are running Helm Operator 1.2.0 with 8 workers and it's only processing about 30 CRDs / minute. For operational reasons, we need this to be at least 3-5x faster, but can't figure out what the bottleneck is or how to speed it up. We've tried increasing workers and changing the chart sync interval with no effect.

Looking at the logs, all of the time seems to be spent in the sync and dry-run upgrade process, maybe 10s per CRD.

Is this normal? Can you suggest how to troubleshoot and speed it up?

Not sure if this is related, but I'm wondering why the Helm Operator chart template creates a read-only `/root/.kube` mount, which seems to disable kubectl caching ([Flux fixed this](https://github.com/fluxcd/flux/pull/1435/files), why isn't this change in Helm Operator?). I have no idea if that actually impacts this issue, it just seems odd and like it could be related.

**Comment by danepowell** [comment]
It looks like other users experience a very similar issue in the context of Flux, though it seems to be more relevant to Helm Operator than Flux: https://github.com/fluxcd/flux/issues/3338

We also improved performance by culling old configmaps from 2500 to 800. This seems to point to Tiller as a bottleneck, as also evidenced by long-running Helm commands.

**Comment by alenkacz** [comment]
@danepowell just out of curiosity, if you suspect it's tiller, did you try to run the same against helm3?

**Comment by danepowell** [comment]
I intend to upgrade to Helm 3 as soon as possible, since that eliminates the dependency on Tiller, but haven't attempted it yet.

I'm a bit of a newbie, but my understanding is that we can't run Helm 3 locally or via Helm Operator without first upgrading it on the cluster.

**Comment by kingdonb** [comment]
Sorry if your issue remains unresolved. The Helm Operator is in maintenance mode, we recommend everybody upgrades to Flux v2 and Helm Controller.

A new release of Helm Operator is out this week, 1.4.4.

We will continue to support Helm Operator in maintenance mode for an indefinite period of time, and eventually archive this repository.

Please be aware that Flux v2 has a vibrant and active developer community who are actively working through minor releases and delivering new features on the way to General Availability for Flux v2.

In the mean time, this repo will still be monitored, but support is basically limited to migration issues only. I will have to close many issues today without reading them all in detail because of time constraints. If your issue is very important, you are welcome to reopen it, but due to staleness of all issues at this point a new report is more likely to be in order. Please open another issue if you have unresolved problems that prevent your migration in the appropriate Flux v2 repo.

Helm Operator releases will continue as possible for a limited time, as a courtesy for those who still cannot migrate yet, but these are strongly not recommended for ongoing production use as our strict adherence to semver backward compatibility guarantees limit many dependencies and we can only upgrade them so far without breaking compatibility. So there are likely known CVEs that cannot be resolved.

We recommend upgrading to Flux v2 which is actively maintained ASAP.

I am going to go ahead and close every issue at once today,
Thanks for participating in Helm Operator and Flux! 💚 💙
