### ISSUE TITLE
HelmChart: dashboards should take a namespace like flux does

### ISSUE THREAD

**Issue by TJM** [fluxcd/helm-operator#580]
**Describe the bug**

When deploying the grafana dashoards, it deploys them into "{{ Release.Namespace }}" instead of the one defined in values.yaml.

**To Reproduce**

```yaml
dashboards:
  enabled: true
  namespace: monitoring
```

NOTE: `namespace: monitoring` was added in hope that it worked, but it did not.

Steps to reproduce the behaviour:
1. Provide the Helm Operator install instructions
2. Provide a HelmRelease example
3. Post the HelmRelease status, you can get this by running `kubectl describe helmrelease <name>`

**Expected behavior**

**Logs**

If applicable, please provide logs. In a standard stand-alone installation, you'd get this by running `kubectl logs deploy/flux-helm-operator -n fluxcd`.

**Additional context**

- Helm Operator version: 1.2.0
- Kubernetes version: 1.15.x
- Git provider: local
- Helm repository provider: Artifactory

This is an issue with the dashboards in the helm chart, not helm operator itself.

EDIT: It looks like the fix is already in the git repo (which is why I thought I could use it) but it is not in the released version of the HelmChart, could we release this, please?

**Comment by kingdonb** [comment]
Sorry if your issue remains unresolved. The Helm Operator is in maintenance mode, we recommend everybody upgrades to Flux v2 and Helm Controller.

A new release of Helm Operator is out this week, 1.4.4.

We will continue to support Helm Operator in maintenance mode for an indefinite period of time, and eventually archive this repository.

Please be aware that Flux v2 has a vibrant and active developer community who are actively working through minor releases and delivering new features on the way to General Availability for Flux v2.

In the mean time, this repo will still be monitored, but support is basically limited to migration issues only. I will have to close many issues today without reading them all in detail because of time constraints. If your issue is very important, you are welcome to reopen it, but due to staleness of all issues at this point a new report is more likely to be in order. Please open another issue if you have unresolved problems that prevent your migration in the appropriate Flux v2 repo.

Helm Operator releases will continue as possible for a limited time, as a courtesy for those who still cannot migrate yet, but these are strongly not recommended for ongoing production use as our strict adherence to semver backward compatibility guarantees limit many dependencies and we can only upgrade them so far without breaking compatibility. So there are likely known CVEs that cannot be resolved.

We recommend upgrading to Flux v2 which is actively maintained ASAP.

I am going to go ahead and close every issue at once today,
Thanks for participating in Helm Operator and Flux! 💚 💙
