### ISSUE TITLE
Consider adding PreserveUnknownFields kubebuilder annotations to HelmValues.Data object

### ISSUE THREAD

**Issue by nitishm** [fluxcd/helm-operator#585]
**Describe the bug**

HelmRelease type spec uses a kubernetes "Unknown" field for `HelmReleaseSpec.Values` (`HelmValues.Data`) which is generally pruned by kubernetes.

I am currently trying to import HelmReleaseSpec type into my custom operator's Resource types, built using `kubebuilder`. However since the upstream object/package is missing the following annotations,
```
	// +kubebuilder:pruning:PreserveUnknownFields
	// +kubebuilder:validation:XPreserveUnknownFields
```
, it ends up pruning the `Values` field in the generated CRDs.

**To Reproduce**

n/a

**Expected behavior**

See the following annotation in the OpenAPIv3 spec section of the generated CRD yaml,

```
values:
  type: object
  x-kubernetes-preserve-unknown-fields: true
```

**Logs**

n/a

**Additional context**

- Helm Operator version: v1.2.0
- Kubernetes version:
```
- Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:28:09Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-14T07:30:52Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
```
- Git provider:
- Helm repository provider:

**Comment by hiddeco** [comment]
Adding this will make it incompatible with Kubernetes `<1.19.x`, and we can thus not accept this change.

The [helm-controller](https://github.com/fluxcd/helm-controller) API however is targeted at newer versions of Kubernetes, and does have the proper validation and/or pruning rules.

**Comment by kingdonb** [comment]
Sorry if your issue remains unresolved. The Helm Operator is in maintenance mode, we recommend everybody upgrades to Flux v2 and Helm Controller.

A new release of Helm Operator is out this week, 1.4.4.

We will continue to support Helm Operator in maintenance mode for an indefinite period of time, and eventually archive this repository.

Please be aware that Flux v2 has a vibrant and active developer community who are actively working through minor releases and delivering new features on the way to General Availability for Flux v2.

In the mean time, this repo will still be monitored, but support is basically limited to migration issues only. I will have to close many issues today without reading them all in detail because of time constraints. If your issue is very important, you are welcome to reopen it, but due to staleness of all issues at this point a new report is more likely to be in order. Please open another issue if you have unresolved problems that prevent your migration in the appropriate Flux v2 repo.

Helm Operator releases will continue as possible for a limited time, as a courtesy for those who still cannot migrate yet, but these are strongly not recommended for ongoing production use as our strict adherence to semver backward compatibility guarantees limit many dependencies and we can only upgrade them so far without breaking compatibility. So there are likely known CVEs that cannot be resolved.

We recommend upgrading to Flux v2 which is actively maintained ASAP.

I am going to go ahead and close every issue at once today,
Thanks for participating in Helm Operator and Flux! 💚 💙
