### ISSUE TITLE
Evicted helm-operator pods, cache GC not working.

### ISSUE THREAD

**Issue by stylius** [fluxcd/helm-operator#595]
**Issue**

Cache GC is not working as expected and the pods get deleted due to disk pressure. Helm Operator version is 1.2.0, so #422  should be included, yet the /root/.cache/helm/repository/ folder is full of "=-charts.txt" and "=-index.yaml" files. The size of the directory reaches 50+GB when it runs out of space on the nodes and get evicted. Disk is filling up at a rate about 0.5GB/hour.

**Details**

| NAME | NAMESPACE | REVISION | UPDATED | STATUS | CHART | APP VERSION |
| --- | --- | --- | --- | --- | --- | --- |
| paas-infrastructure-helm-operator | paas-infrastructure | 8 | 2021-03-12 09:55:27.665938 +0200 EET | deployed | helm-operator-1.2.0 | 1.2.0 |

```$ helm get values paas-infrastructure-helm-operator
USER-SUPPLIED VALUES:
allowNamespace: paas-infrastructure
chartsSyncInterval: 1m
clusterRole:
  create: true
configureRepositories:
  enable: true
  repositories:
  - name: stable
    url: https://charts.helm.sh/stable
helm:
  versions: v3
image:
  repository: docker.io/fluxcd/helm-operator
  tag: 1.2.0
kube:
  config: '{apiVersion: v1, clusters: [], contexts: [{context: {cluster: "", namespace: "paas-infrastructure", user: ""}, name: ""}], current-context: "", kind: Config, preferences: {}, users: []}'
updateChartDeps: false
workers: 1
```

```
$ date && kubectl exec -ti deploy/paas-infrastructure-helm-operator -c flux-helm-operator -- du -h /root/.cache/helm/repository
Fri Mar 12 10:29:27 EET 2021
413.5M	/root/.cache/helm/repository

Fri Mar 12 10:55:02 EET 2021
660.1M	/root/.cache/helm/repository
```

**Comment by kingdonb** [comment]
Sorry if your issue remains unresolved. The Helm Operator is in maintenance mode, we recommend everybody upgrades to Flux v2 and Helm Controller.

A new release of Helm Operator is out this week, 1.4.4.

We will continue to support Helm Operator in maintenance mode for an indefinite period of time, and eventually archive this repository.

Please be aware that Flux v2 has a vibrant and active developer community who are actively working through minor releases and delivering new features on the way to General Availability for Flux v2.

In the mean time, this repo will still be monitored, but support is basically limited to migration issues only. I will have to close many issues today without reading them all in detail because of time constraints. If your issue is very important, you are welcome to reopen it, but due to staleness of all issues at this point a new report is more likely to be in order. Please open another issue if you have unresolved problems that prevent your migration in the appropriate Flux v2 repo.

Helm Operator releases will continue as possible for a limited time, as a courtesy for those who still cannot migrate yet, but these are strongly not recommended for ongoing production use as our strict adherence to semver backward compatibility guarantees limit many dependencies and we can only upgrade them so far without breaking compatibility. So there are likely known CVEs that cannot be resolved.

We recommend upgrading to Flux v2 which is actively maintained ASAP.

I am going to go ahead and close every issue at once today,
Thanks for participating in Helm Operator and Flux! 💚 💙
