### ISSUE TITLE
Helm Operator throws `error converting YAML to JSON`

### ISSUE THREAD

**Issue by cwrau** [fluxcd/helm-operator#596]
**Describe the bug**

Helm Operator throws `error converting YAML to JSON`, although helm and yq + jq work fine.

I manually upgraded via helm, hoping the operator would just work afterwards, but it still throws the error

**To Reproduce**

Steps to reproduce the behaviour:
1. Create Helm Release with attached YAML: [prometheus-operator.txt](https://github.com/fluxcd/helm-operator/files/6148440/prometheus-operator.txt)
2. Observe it failing with the below error message
     ```
     Warning  FailedReleaseSync  14m (x2 over 22m)      helm-operator  synchronization of release 'prometheus-operator' in namespace 'monitoring' failed: dry-run upgrade failed: dry-run upgrade for comparison failed: YAML parse error on kube-prometheus-stack/charts/grafana/templates/configmap.yaml: error converting YAML to JSON: yaml: line 30: did not find expected comment or line break
     ```

**Expected behavior**

It upgrading my release

**Logs**

```
ts=2021-03-16T11:01:20.631533525Z caller=release.go:79 component=release release=prometheus-operator targetNamespace=monitoring resource=flux:helmrelease/prometheus-operator helmVersion=v3 info="starting sync run"
ts=2021-03-16T11:01:23.865408638Z caller=release.go:289 component=release release=prometheus-operator targetNamespace=monitoring resource=flux:helmrelease/prometheus-operator helmVersion=v3 info="running dry-run upgrade to compare with release version '15'" action=dry-run-compare
ts=2021-03-16T11:01:23.912520717Z caller=helm.go:69 component=helm version=v3 info="preparing upgrade for prometheus-operator" targetNamespace=monitoring release=prometheus-operator
ts=2021-03-16T11:01:24.243413947Z caller=helm.go:69 component=helm version=v3 info="resetting values to the chart's original version" targetNamespace=monitoring release=prometheus-operator
ts=2021-03-16T11:01:30.542756581Z caller=release.go:294 component=release release=prometheus-operator targetNamespace=monitoring resource=flux:helmrelease/prometheus-operator helmVersion=v3 error="dry-run upgrade for comparison failed: YAML parse error on kube-prometheus-stack/charts/grafana/templates/configmap.yaml: error converting YAML to JSON: yaml: line 30: did not find expected comment or line break" phase=dry-run-compare
```

**Additional context**

- Helm Operator version: 1.2.0
- Kubernetes version: 1.18.8
- Git provider: ---
- Helm repository provider: https://prometheus-community.github.io/helm-charts

**Comment by cwrau** [comment]
Can I do something to help with debugging?

**Comment by r-catania** [comment]
I believe the issue is caused by the || in  role_attribute_path: .
We are seeing the same issue while trying to deploy grafana. 
Issue could be related to this https://github.com/grafana/helm-charts/issues/270 
According to that helm version 3.5.2 does not experience the problem.

**Comment by cwrau** [comment]
Ah, that's unfortunate

If it's the right workflow, you can close this issue, otherwise I'll try to remember to close this when the other issue gets resolved

**Comment by kingdonb** [comment]
Sorry if your issue remains unresolved. The Helm Operator is in maintenance mode, we recommend everybody upgrades to Flux v2 and Helm Controller.

A new release of Helm Operator is out this week, 1.4.4.

We will continue to support Helm Operator in maintenance mode for an indefinite period of time, and eventually archive this repository.

Please be aware that Flux v2 has a vibrant and active developer community who are actively working through minor releases and delivering new features on the way to General Availability for Flux v2.

In the mean time, this repo will still be monitored, but support is basically limited to migration issues only. I will have to close many issues today without reading them all in detail because of time constraints. If your issue is very important, you are welcome to reopen it, but due to staleness of all issues at this point a new report is more likely to be in order. Please open another issue if you have unresolved problems that prevent your migration in the appropriate Flux v2 repo.

Helm Operator releases will continue as possible for a limited time, as a courtesy for those who still cannot migrate yet, but these are strongly not recommended for ongoing production use as our strict adherence to semver backward compatibility guarantees limit many dependencies and we can only upgrade them so far without breaking compatibility. So there are likely known CVEs that cannot be resolved.

We recommend upgrading to Flux v2 which is actively maintained ASAP.

I am going to go ahead and close every issue at once today,
Thanks for participating in Helm Operator and Flux! 💚 💙
