### ISSUE TITLE
Require image for ARM64 architecture

### ISSUE THREAD

**Issue by odidev** [fluxcd/helm-operator#633]
Hi Team, 
I am trying to use the **fluxcd/helm-operator** image on the arm64 platform but it seems it is not available for arm64. 

I have successfully built the image using the command **make all** on the arm64 platform by making some changes in the files **Makefile, Dockerfile.helm-operator** and c**ircleci/config.yml**. 

I have used **Circle-CI** to build and push the image for both the platforms. 

**Commit Link -** https://github.com/odidev/helm-operator/commit/bfe73f6cb18639932c7b87de2ecd6d012163bd2a

**Circle-CI link -** https://app.circleci.com/pipelines/github/odidev/helm-operator/2/workflows/60e927e2-d284-4e55-bcc9-d3f6d2a9b326/jobs/2 

**Docker Hub Link -** https://hub.docker.com/repository/registry-1.docker.io/odidev/helm-operator/tags?page=1&ordering=last_updated 

Do you have any plans on releasing arm64 images? 

It will be very helpful if an arm64 image is available. If interested, I will raise a PR.

**Comment by yebyen** [comment]
Thank you for putting this out there!

The helm operator project is superseded by Helm Controller, which is in active development and supports armhf and arm64.

https://fluxcd.io/docs/migration/timetable/

Is there anything stopping you from migration to the Flux v2 codebase, which is actively developed?

According to the migration timetable we should not be accepting or developing any new features or bugfixes for Helm Operator, unless they are related to an expression of some CVE. But as this is open source you are free to do with it as you wish, including publishing your own images. We can certainly take a look at your PR and provide feedback. Does it publish a multi-arch format?

**Comment by kingdonb** [comment]
Is this support provided by a fork actively used by anyone that can vouch for its working status, or not?

**Comment by kingdonb** [comment]
Sorry if your issue remains unresolved. The Helm Operator is in maintenance mode, we recommend everybody upgrades to Flux v2 and Helm Controller.

A new release of Helm Operator is out this week, 1.4.4.

We will continue to support Helm Operator in maintenance mode for an indefinite period of time, and eventually archive this repository.

Please be aware that Flux v2 has a vibrant and active developer community who are actively working through minor releases and delivering new features on the way to General Availability for Flux v2.

In the mean time, this repo will still be monitored, but support is basically limited to migration issues only. I will have to close many issues today without reading them all in detail because of time constraints. If your issue is very important, you are welcome to reopen it, but due to staleness of all issues at this point a new report is more likely to be in order. Please open another issue if you have unresolved problems that prevent your migration in the appropriate Flux v2 repo.

Helm Operator releases will continue as possible for a limited time, as a courtesy for those who still cannot migrate yet, but these are strongly not recommended for ongoing production use as our strict adherence to semver backward compatibility guarantees limit many dependencies and we can only upgrade them so far without breaking compatibility. So there are likely known CVEs that cannot be resolved.

We recommend upgrading to Flux v2 which is actively maintained ASAP.

I am going to go ahead and close every issue at once today,
Thanks for participating in Helm Operator and Flux! 💚 💙
