### ISSUE TITLE
fluxcd/helm-operator 1.4.3 not available on dockerhub

### ISSUE THREAD

**Issue by gionn** [fluxcd/helm-operator#657]
**Describe the bug**

The freshly released [1.4.3](https://github.com/fluxcd/helm-operator/releases/tag/1.4.3) is missing on docker hub:

https://hub.docker.com/r/fluxcd/helm-operator/tags

That is causing the inability to install helm-operator via latest available chart version:

```
Back-off pulling image "docker.io/fluxcd/helm-operator:1.4.3
```

**Comment by gionn** [comment]
Tag has been published on Jul 27, 2022 at 6:57 pm

at least I have discovered we were not pinning flux v1 versions =D

**Comment by kingdonb** [comment]
Yes, thank you for reporting 🌮 

We noticed almost right away that the release CI wasn't triggering. This is an unfortunate side-effect of broadening the maintainer pool again, we discover things which were undocumented and one of them was as is covered by this change:

* https://github.com/fluxcd/helm-operator/pull/658

We are not expecting any more Helm Operator maintainers necessarily as due to the maintenance status, but sometimes surprises do arise:

* https://github.com/fluxcd/flux/issues/3320

Please consider migrating to Flux v2 and Helm Controller (or even just Helm Controller+Source Controller, which has many advancements that cannot be backported to Helm Operator and generally gets more regular maintenance and attention.)
