### ISSUE TITLE
Git over HTTPS support

### ISSUE THREAD

**Issue by masterkain** [fluxcd/helm-operator#94]
Helm Operator allows for recycling the git ssh key eventually used in a Flux setup, however Flux does also support Git over HTTPS to fetch its state:
https://github.com/fluxcd/flux/blob/master/chart/flux/README.md#flux-with-git-over-https
which is the method I initially adopted.

However as per Helm Operator's readme the only method supported is the git deploy key:
https://github.com/fluxcd/helm-operator/blob/master/chart/helm-operator/README.md#use-fluxs-git-deploy-key

Is using `flux-git-auth` instead of `flux-git-deploy` supported somehow? In any case how would the `spec.chart.git` entry look like in our HelmRelease?

**Comment by jbuettnerbild** [comment]
i have the same problem. i don't want to configure flux and the helm operator differently. One time with git username and token and otherwise with a ssh key.

**Comment by mmaask** [comment]
This should be supported indeed. Currently helm operator git clones are all getting access denied.

**Comment by hiddeco** [comment]
The only way this would work at the moment is if one would provide plain credentials in the `HelmRelease` `spec.chart.git` entry. The reason this is not required for Flux is because Flux is able to utilize the [variable substitution built in to Kubernetes](https://kubernetes.io/docs/tasks/inject-data-application/define-environment-variable-container/#using-environment-variables-inside-of-your-config), something that is not possible using custom resources.

To make this possible without leaking credentials in a `HelmRelease` resource we need to come up with a secure and straight forward way to provide a reference to a secret containing the credentials, and add them to the parsed `spec.chart.git` URL before we request a new Git mirror.

This will likely also include some brain gymnastics around mirror names as this equals to the `spec.chart.git` value at the moment to re-use git mirrors cross releases. To prevent leaking access across `HelmRelease` resources and/or namespaces this would need a reference to the credentials being referred to and/or namespace the resource is in (or e.g. a simple checksum of all values combined).

**Comment by chancez** [comment]
Could you not just support configuring helm-operator with a single set of credentials and simply use them during cloning if present? I think supporting creds per-HelmRelease CR is a nice-to-have, but being able to simply specify HTTPS credentials (via env) to helm-operator would suffice for many use-cases. In fact, you could probably even just use `os.ExpandEnv` on the URI and call it a day, and we could then use env vars in the URI and it would expand them the way anyone expects.

**Comment by hiddeco** [comment]
@chancez you can not simply use `os.ExpandEnv` on an URL as [`$` is a reserved character (sub-delim) according to RFC3986](https://tools.ietf.org/html/rfc3986#section-2.2) and it is thus possible that a value in an URL is also present as an environmental variable, causing an accidental replace.

**Comment by chancez** [comment]
Fair enough.

**Comment by hiddeco** [comment]
This was implemented in #172 (thanks again @richardcase! :tulip:)
