### ISSUE TITLE
Filter namespaces by annotation rather than `--allow-namespace`

### ISSUE THREAD

**Issue by jdfalk** [fluxcd/helm-operator#96]
**Describe the feature**
Create an annotation like `helm.fluxcd.io/enabled`: `false` instead of using the specify namespace field. This follows the patterns of other major k8s projects like flux `fluxcd.io/automated: "false"`, istio, jaeger, certmanager, etc.

**Background**
We have a multi-tenant  cluster where we want to have two completely separate instances of tiller, flux, flux-helm-operator. We would like the flux-helm-operator managed by ops/eng to have access to all namespaces outside of the developers' namespaces so that we don't trample on their instances.

**Workaround**
Restrict `flux-helm-operator` to `flux` namespace, and use the `targetNamespace` field to deploy things into other namespaces.

**What would the new user story look like?**
How would the new interaction with the Flux Helm operator look like? E.g.
0. By default all namespaces would be enabled, the annotation would only disable namespaces. -- Make this configurable by users.
1. User creates namespace that they don't want helm-operator to process and annotates it as `helm.fluxcd.io/enabled`: `false`. 
2. A new `HelmRelease` is mistakenly created in that namespace.
3. Flux notes the release and rejects it due to namespace conditions.

**Expected behavior**
Flux retrieves all namespaces and reads annotations. Any namespace annotated with specific annotation are dropped from processing but releases are noted in the log.

**Comment by kingdonb** [comment]
Sorry if your issue remains unresolved. The Helm Operator is in maintenance mode, we recommend everybody upgrades to Flux v2 and Helm Controller.

A new release of Helm Operator is out this week, 1.4.4.

We will continue to support Helm Operator in maintenance mode for an indefinite period of time, and eventually archive this repository.

Please be aware that Flux v2 has a vibrant and active developer community who are actively working through minor releases and delivering new features on the way to General Availability for Flux v2.

In the mean time, this repo will still be monitored, but support is basically limited to migration issues only. I will have to close many issues today without reading them all in detail because of time constraints. If your issue is very important, you are welcome to reopen it, but due to staleness of all issues at this point a new report is more likely to be in order. Please open another issue if you have unresolved problems that prevent your migration in the appropriate Flux v2 repo.

Helm Operator releases will continue as possible for a limited time, as a courtesy for those who still cannot migrate yet, but these are strongly not recommended for ongoing production use as our strict adherence to semver backward compatibility guarantees limit many dependencies and we can only upgrade them so far without breaking compatibility. So there are likely known CVEs that cannot be resolved.

We recommend upgrading to Flux v2 which is actively maintained ASAP.

I am going to go ahead and close every issue at once today,
Thanks for participating in Helm Operator and Flux! 💚 💙
